import { emoji, aliases, translations } from 'pretty-text/emoji/data';

// bump up this number to expire all emojis
export const IMAGE_VERSION = "3";

const extendedEmoji = {};
var championName = {
    "aatrox": "Aatrox",
    "ahri": "Ahri",
    "akali": "Akali",
    "alistar": "Alistar",
    "amumu": "Amumu",
    "anivia": "Anivia",
    "annie": "Annie",
    "ashe": "Ashe",
    "aurelionsol": "AurelionSol",
    "azir": "Azir",
    "bard": "Bard",
    "blitzcrank": "Blitzcrank",
    "brand": "Brand",
    "braum": "Braum",
    "caitlyn": "Caitlyn",
    "cassiopeia": "Cassiopeia",
    "chogath": "Chogath",
    "corki": "Corki",
    "darius": "Darius",
    "diana": "Diana",
    "draven": "Draven",
    "drmundo": "DrMundo",
    "ekko": "Ekko",
    "elise": "Elise",
    "evelynn": "Evelynn",
    "ezreal": "Ezreal",
    "fiddlesticks": "FiddleSticks",
    "fiora": "Fiora",
    "fizz": "Fizz",
    "galio": "Galio",
    "gangplank": "Gangplank",
    "garen": "Garen",
    "gnar": "Gnar",
    "gragas": "Gragas",
    "graves": "Graves",
    "hecarim": "Hecarim",
    "heimerdinger": "Heimerdinger",
    "illaoi": "Illaoi",
    "irelia": "Irelia",
    "ivern": "Ivern",
    "janna": "Janna",
    "jarvaniv": "JarvanIV",
    "jax": "Jax",
    "jayce": "Jayce",
    "jhin": "Jhin",
    "jinx": "Jinx",
    "kalista": "Kalista",
    "karma": "Karma",
    "karthus": "Karthus",
    "kassadin": "Kassadin",
    "katarina": "Katarina",
    "kayle": "Kayle",
    "kennen": "Kennen",
    "khazix": "Khazix",
    "kindred": "Kindred",
    "kled": "Kled",
    "kogmaw": "KogMaw",
    "leblanc": "Leblanc",
    "leesin": "LeeSin",
    "leona": "Leona",
    "lissandra": "Lissandra",
    "lucian": "Lucian",
    "lulu": "Lulu",
    "lux": "Lux",
    "malphite": "Malphite",
    "malzahar": "Malzahar",
    "maokai": "Maokai",
    "masteryi": "MasterYi",
    "missfortune": "MissFortune",
    "monkeyking": "MonkeyKing",
    "mordekaiser": "Mordekaiser",
    "morgana": "Morgana",
    "nami": "Nami",
    "nasus": "Nasus",
    "nautilus": "Nautilus",
    "nidalee": "Nidalee",
    "nocturne": "Nocturne",
    "nunu": "Nunu",
    "olaf": "Olaf",
    "orianna": "Orianna",
    "pantheon": "Pantheon",
    "poppy": "Poppy",
    "quinn": "Quinn",
    "rammus": "Rammus",
    "reksai": "RekSai",
    "renekton": "Renekton",
    "rengar": "Rengar",
    "riven": "Riven",
    "rumble": "Rumble",
    "ryze": "Ryze",
    "sejuani": "Sejuani",
    "shaco": "Shaco",
    "shen": "Shen",
    "shyvana": "Shyvana",
    "singed": "Singed",
    "sion": "Sion",
    "sivir": "Sivir",
    "skarner": "Skarner",
    "sona": "Sona",
    "soraka": "Soraka",
    "swain": "Swain",
    "syndra": "Syndra",
    "tahmkench": "TahmKench",
    "taliyah": "Taliyah",
    "talon": "Talon",
    "taric": "Taric",
    "teemo": "Teemo",
    "thresh": "Thresh",
    "tristana": "Tristana",
    "trundle": "Trundle",
    "tryndamere": "Tryndamere",
    "twistedfate": "TwistedFate",
    "twitch": "Twitch",
    "udyr": "Udyr",
    "urgot": "Urgot",
    "varus": "Varus",
    "vayne": "Vayne",
    "veigar": "Veigar",
    "velkoz": "Velkoz",
    "vi": "Vi",
    "viktor": "Viktor",
    "vladimir": "Vladimir",
    "volibear": "Volibear",
    "warwick": "Warwick",
    "xerath": "Xerath",
    "xinzhao": "XinZhao",
    "yasuo": "Yasuo",
    "yorick": "Yorick",
    "zac": "Zac",
    "zed": "Zed",
    "ziggs": "Ziggs",
    "zilean": "Zilean",
    "zyra": "Zyra",
    "fury": "Fury",
    "no": "Nộ",
    "sorcery": "Sorcery",
    "ma-thuat": "Ma Thuật",
    "fresh-blood": "Fresh Blood",
    "phu-dau": "Phủ Đầu",
    "feast": "Feast",
    "nuot-chung": "Nuốt Chửng",
    "expose-weakness": "Expose Weakness",
    "cong-kich-yeu-diem": "Công Kích Yếu Điểm",
    "vampirism": "Vampirism",
    "hap-huyet": "Hấp Huyết",
    "natural-talent": "Natural Talent",
    "tai-nang-thien-bam": "Tài Năng Thiên Bẩm",
    "bounty-hunter": "Bounty Hunter",
    "tho-san-tien-thuong": "Thợ Săn Tiền Thưởng",
    "double-edged-sword": "Double Edged Sword",
    "guom-hai-luoi": "Gươm Hai Lưỡi",
    "battle-trance": "Battle Trance",
    "hang-mau": "Hăng Máu",
    "battering-blows": "Battering Blows",
    "dap-lien-hoi": "Đập Liên Hồi",
    "piercing-thoughts": "Piercing Thoughts",
    "tia-chop-xuyen-thau": "Tia Chớp Xuyên Thấu",
    "warlords-bloodlust": "Warlord's Bloodlust",
    "cuong-huyet-chien-tuong": "Cuồng Huyết Chiến Tướng",
    "fervor-of-battle": "Fervor of Battle",
    "nhiet-huyet-chien-dau": "Nhiệt Huyết Chiến Đấu",
    "deathfire-touch": "Deathfire Touch",
    "lua-tu-than": "Lửa Tử Thần",
    "recovery": "Recovery",
    "phuc-hoi": "Phục Hồi",
    "unyielding": "Unyielding",
    "bat-khuat": "Bất Khuất",
    "explorer": "Explorer",
    "tham-hiem": "Thám Hiểm",
    "siegemaster": "Siegemaster",
    "bac-thay-phong-ngu": "Bậc Thầy Phòng Ngự",
    "tough-skin": "Tough Skin",
    "deo-dai": "Dẻo Dai",
    "runic-armor": "Runic Armor",
    "giap-co-ngu": "Giáp Cổ Ngữ",
    "veterans-scars": "Veteran's Scars",
    "seo-chien-tranh": "Sẹo Chiến Tranh",
    "insight": "Insight",
    "sang-suot": "Sáng Suốt",
    "perseverance": "Perseverance",
    "ben-bi": "Bền Bỉ",
    "fearless": "Fearless",
    "can-dam": "Can Đảm",
    "swiftness": "Swiftness",
    "nhanh-nhen": "Nhanh Nhẹn",
    "legendary-guardian": "Legendary Guardian",
    "than-ho-menh-huyen-thoai": "Thần Hộ Mệnh Huyền Thoại",
    "grasp-of-the-undying": "Grasp of the Undying",
    "quyen-nang-bat-diet": "Quyền Năng Bất Diệt",
    "courage-of-the-colossus": "Courage of the Colossus",
    "dung-khi-khong-lo": "Dũng Khí Khổng Lồ",
    "bond-of-stone": "Bond of Stone",
    "lien-ket-sat-da": "Liên Kết Sắt Đá",
    "wanderer": "Wanderer",
    "lang-khach": "Lãng Khách",
    "savagery": "Savagery",
    "tan-bao": "Tàn Bạo",
    "runic-affinity": "Runic Affinity",
    "dam-me-co-ngu": "Đam Mê Cổ Ngữ",
    "secret-stash": "Secret Stash",
    "hanh-nang-bi-mat": "Hành Nang Bí Mật",
    "assassin": "Assassin",
    "thich-khach": "Thích Khách",
    "merciless": "Merciless",
    "tan-nhan": "Tàn Nhẫn",
    "meditation": "Meditation",
    "thien-dinh": "Thiền Định",
    "greenfathers-gift": "Greenfather's Gift",
    "qua-tang-thien-nhien": "Quà Tặng Thiên Nhiên",
    "bandit": "Bandit",
    "dao-tac": "Đạo Tặc",
    "dangerous-game": "Dangerous Game",
    "tro-choi-nguy-hiem": "Trò Chơi Nguy Hiểm",
    "precision": "Precision",
    "chuan-xac": "Chuẩn Xác",
    "intelligence": "Intelligence",
    "thong-tue": "Thông Tuệ",
    "stormraiders-surge": "Stormraider's Surge",
    "xung-kich-bao-to": "Xung Kích Bão Tố",
    "thunderlords-decree": "Thunderlord's Decree",
    "y-chi-than-sam": "Ý Chỉ Thần Sấm",
    "windspeakers-blessing": "Windspeaker's Blessing",
    "phong-ngon-chuc-phuc": "Phong Ngôn Chúc Phúc",
    "boots-of-speed": "Boots of Speed",
    "giay-thuong": "Giày Thường",
    "faerie-charm": "Faerie Charm",
    "bua-tien": "Bùa Tiên",
    "rejuvenation-bead": "Rejuvenation Bead",
    "ngoc-luc-bao": "Ngọc Lục Bảo",
    "giants-belt": "Giant's Belt",
    "dai-khong-lo": "Đai Khổng Lồ",
    "cloak-of-agility": "Cloak of Agility",
    "ao-choang-tim": "Áo Choàng Tím",
    "blasting-wand": "Blasting Wand",
    "gay-bung-no": "Gậy Bùng Nổ",
    "sapphire-crystal": "Sapphire Crystal",
    "lam-ngoc": "Lam Ngọc",
    "ruby-crystal": "Ruby Crystal",
    "hong-ngoc": "Hồng Ngọc",
    "cloth-armor": "Cloth Armor",
    "giap-lua": "Giáp Lụa",
    "chain-vest": "Chain Vest",
    "giap-luoi": "Giáp Lưới",
    "null-magic-mantle": "Null-Magic Mantle",
    "ao-vai": "Áo Vải",
    "long-sword": "Long Sword",
    "kiem-dai": "Kiếm Dài",
    "pickaxe": "Pickaxe",
    "cuoc-chim": "Cuốc Chim",
    "b.f.sword": "B. F. Sword",
    "kiem-b.f.": "Kiếm B.F.",
    "hunters-talisman": "Hunter's Talisman",
    "bua-tho-san-": "Bùa Thợ Săn ",
    "hunters-machete": "Hunter's Machete",
    "rua-tho-san": "Rựa Thợ Săn",
    "dagger": "Dagger",
    "dao-gam": "Dao Găm",
    "recurve-bow": "Recurve Bow",
    "cung-go": "Cung Gỗ",
    "brawlers-gloves": "Brawler's Gloves",
    "gang-tay-gai": "Găng Tay Gai",
    "amplifying-tome": "Amplifying Tome",
    "sach-cu": "Sách Cũ",
    "vampiric-scepter": "Vampiric Scepter",
    "huyet-truong": "Huyết Trượng",
    "dorans-shield": "Doran's Shield",
    "khien-doran": "Khiên Doran",
    "dorans-blade": "Doran's Blade",
    "kiem-doran": "Kiếm Doran",
    "dorans-ring": "Doran's Ring",
    "nhan-doran": "Nhẫn Doran",
    "negatron-cloak": "Negatron Cloak",
    "ao-choang-bac": "Áo Choàng Bạc",
    "needlessly-large-rod": "Needlessly Large Rod",
    "gay-qua-kho": "Gậy Quá Khổ",
    "the-dark-seal": "The Dark Seal",
    "phong-an-hac-am": "Phong Ấn Hắc Ám",
    "cull": "Cull",
    "luoi-hai": "Lưỡi Hái",
    "enchantment-warrior": "Enchantment: Warrior",
    "phu-phep-chien-binh": "Phù Phép: Chiến Binh",
    "enchantment-cinderhulk": "Enchantment: Cinderhulk",
    "phu-phep-quy-lua": "Phù Phép: Quỷ Lửa",
    "enchantment-runic-echoes": "Enchantment: Runic Echoes",
    "phu-phep-than-vong": "Phù Phép: Thần Vọng",
    "enchantment-bloodrazor": "Enchantment: Bloodrazor",
    "phu-phep-huyet-dao": "Phù Phép: Huyết Đao",
    "health-potion": "Health Potion",
    "binh-mau": "Bình Máu",
    "total-biscuit-of-rejuvenation": "Total Biscuit of Rejuvenation",
    "banh-qui-total-biscuit-": "Bánh Qui Total Biscuit ",
    "total-biscuit-hoi-xuan": "Total Biscuit Hồi Xuân",
    "kircheis-shard": "Kircheis Shard",
    "manh-vo-kircheis": "Mảnh Vỡ Kircheis",
    "refillable-potion": "Refillable Potion",
    "thuoc-tai-su-dung": "Thuốc Tái Sử Dụng",
    "hunters-potion": "Hunter's Potion",
    "thuoc-cua-tho-san": "Thuốc Của Thợ Săn",
    "corrupting-potion": "Corrupting Potion",
    "binh-thuoc-bien-di": "Bình Thuốc Biến Dị",
    "ruby-sightstone": "Ruby Sightstone",
    "hong-ngoc-toa-sang-": "Hồng Ngọc Tỏa Sáng ",
    "oracles-extract": "Oracle's Extract",
    "chiet-xuat-oracle": "Chiết Xuất Oracle",
    "sightstone": "Sightstone",
    "da-toa-sang": "Đá Tỏa Sáng",
    "explorers-ward": "Explorer's Ward",
    "mat-tham-hiem": "Mắt Thám Hiểm",
    "guardians-horn": "Guardian's Horn",
    "tu-va-ve-quan": "Tù Và Vệ Quân",
    "poro-snax": "Poro-Snax",
    "raptor-cloak": "Raptor Cloak",
    "ao-choang-khung-long": "Áo Choàng Khủng Long",
    "diet-poro-snax": "Diet Poro-Snax",
    "poro-snax-giam-can": "Poro-Snax Giảm Cân",
    "control-ward": "Control Ward",
    "mat-kiem-soat": "Mắt Kiểm Soát",
    "elixir-of-iron": "Elixir of Iron",
    "duoc-pham-cung-cap": "Dược Phẩm Cứng Cáp",
    "elixir-of-sorcery": "Elixir of Sorcery",
    "duoc-pham-thuat-phap": "Dược Phẩm Thuật Pháp",
    "elixir-of-wrath": "Elixir of Wrath",
    "duoc-pham-phan-no": "Dược Phẩm Phẫn Nộ",
    "eye-of-the-watchers": "Eye of the Watchers",
    "mat-giam-sat": "Mắt Giám Sát",
    "eye-of-the-oasis": "Eye of the Oasis",
    "mat-oc-dao": "Mắt Ốc Đảo",
    "eye-of-the-equinox": "Eye of the Equinox",
    "mat-ma-thuat": "Mắt Ma Thuật",
    "abyssal-scepter": "Abyssal Scepter",
    "gay-dau-lau": "Gậy Đầu Lâu",
    "archangels-staff": "Archangel's Staff",
    "quyen-truong-thien-than": "Quyền Trượng Thiên Thần",
    "manamune": "Manamune",
    "kiem-manamune": "Kiếm Manamune",
    "berserkers-greaves": "Berserker's Greaves",
    "giay-cuong-no": "Giày Cuồng Nộ",
    "archangels-staff-quick-charge": "Archangel's Staff (Quick Charge)",
    "quyen-truong-thien-than-nap-nhanh": "Quyền Trượng Thiên Thần (Nạp Nhanh)",
    "manamune-quick-charge": "Manamune (Quick Charge)",
    "kiem-manamune-nap-nhanh": "Kiếm Manamune (Nạp Nhanh)",
    "boots-of-swiftness": "Boots of Swiftness",
    "giay-bac": "Giày Bạc",
    "catalyst-of-aeons": "Catalyst of Aeons",
    "da-vinh-hang": "Đá Vĩnh Hằng",
    "sorcerers-shoes": "Sorcerer's Shoes",
    "giay-phap-su": "Giày Pháp Sư",
    "frozen-mallet": "Frozen Mallet",
    "bua-bang": "Búa Băng",
    "glacial-shroud": "Glacial Shroud",
    "khien-manh-su": "Khiên Mãnh Sư",
    "iceborn-gauntlet": "Iceborn Gauntlet",
    "gang-tay-bang-gia": "Găng Tay Băng Giá",
    "guardian-angel": "Guardian Angel",
    "giap-thien-than": "Giáp Thiên Thần",
    "rod-of-ages": "Rod of Ages",
    "truong-truong-sinh": "Trượng Trường Sinh",
    "chalice-of-harmony": "Chalice of Harmony",
    "coc-hai-hoa": "Cốc Hài Hòa",
    "rod-of-ages-quick-charge": "Rod of Ages (Quick Charge)",
    "truong-truong-sinh-nap-nhanh": "Trượng Trường Sinh (Nạp Nhanh)",
    "hextech-glp800": "Hextech GLP-800",
    "sung-ngan-hextech": "Súng Ngắn Hextech",
    "infinity-edge": "Infinity Edge",
    "vo-cuc-kiem": "Vô Cực Kiếm",
    "mortal-reminder": "Mortal Reminder",
    "loi-nhac-tu-vong": "Lời Nhắc Tử Vong",
    "giant-slayer": "Giant Slayer",
    "diet-khong-lo": "Diệt Khổng Lồ",
    "last-whisper": "Last Whisper",
    "cung-xanh": "Cung Xanh",
    "lord-dominiks-regards": "Lord Dominik's Regards",
    "no-than-dominik": "Nỏ Thần Dominik",
    "seraphs-embrace": "Seraph's Embrace",
    "quyen-truong-dai-thien-su": "Quyền Trượng Đại Thiên Sứ",
    "mejais-soulstealer": "Mejai's Soulstealer",
    "sach-chieu-hon-mejai": "Sách Chiêu Hồn Mejai",
    "muramana": "Muramana",
    "than-kiem-muramana": "Thần Kiếm Muramana",
    "phage": "Phage",
    "bua-go": "Búa Gỗ",
    "phantom-dancer": "Phantom Dancer",
    "ma-vu-song-kiem": "Ma Vũ Song Kiếm",
    "ninja-tabi": "Ninja Tabi",
    "giay-ninja": "Giày Ninja",
    "zekes-harbinger": "Zeke's Harbinger",
    "diem-bao-zeke": "Điềm Báo Zeke",
    "jaurims-fist": "Jaurim's Fist",
    "nam-dam-cua-jaurim": "Nắm Đấm của Jaurim",
    "steraks-gage": "Sterak's Gage",
    "mong-vuot-sterak": "Móng Vuốt Sterak",
    "ohmwrecker": "Ohmwrecker",
    "nhieu-truong-ohmwrecker": "Nhiễu Trượng Ohmwrecker",
    "sheen": "Sheen",
    "thuy-kiem": "Thủy Kiếm",
    "banner-of-command": "Banner of Command",
    "co-lenh-hieu-trieu": "Cờ Lệnh Hiệu Triệu",
    "spirit-visage": "Spirit Visage",
    "giap-tam-linh": "Giáp Tâm Linh",
    "kindlegem": "Kindlegem",
    "hoa-ngoc": "Hỏa Ngọc",
    "sunfire-cape": "Sunfire Cape",
    "ao-choang-lua": "Áo Choàng Lửa",
    "talisman-of-ascension": "Talisman of Ascension",
    "bua-thang-hoa": "Bùa Thăng Hoa",
    "tear-of-the-goddess": "Tear of the Goddess",
    "nuoc-mat-nu-than": "Nước Mắt Nữ Thần",
    "the-black-cleaver": "The Black Cleaver",
    "riu-den": "Rìu Đen",
    "the-bloodthirster": "The Bloodthirster",
    "huyet-kiem": "Huyết Kiếm",
    "tear-of-the-goddess-quick-charge": "Tear of the Goddess (Quick Charge)",
    "nuoc-mat-nu-than-nap-nhanh": "Nước Mắt Nữ Thần (Nạp Nhanh)",
    "ravenous-hydra": "Ravenous Hydra",
    "riu-mang-xa-chi-can-chien": "Rìu Mãng Xà (Chỉ cận chiến)",
    "thornmail": "Thornmail",
    "giap-gai": "Giáp Gai",
    "tiamat": "Tiamat",
    "riu-tiamat-chi-can-chien": "Rìu Tiamat (Chỉ cận chiến)",
    "trinity-force": "Trinity Force",
    "tam-hop-kiem": "Tam Hợp Kiếm",
    "wardens-mail": "Warden's Mail",
    "giap-cai-nguc": "Giáp Cai Ngục",
    "warmogs-armor": "Warmog's Armor",
    "giap-mau-warmog": "Giáp Máu Warmog",
    "overlords-bloodmail": "Overlord's Bloodmail",
    "huyet-giap-chua-te": "Huyết Giáp Chúa Tể",
    "runaans-hurricane": "Runaan's Hurricane",
    "cuong-cung-runaan-chi-danh-xa": "Cuồng Cung Runaan (Chỉ Đánh Xa)",
    "zeal": "Zeal",
    "song-kiem": "Song Kiếm",
    "statikk-shiv": "Statikk Shiv",
    "dao-dien-statikk": "Dao Điện Statikk",
    "rabadons-deathcap": "Rabadon's Deathcap",
    "mu-phu-thuy-rabadon": "Mũ Phù Thủy Rabadon",
    "wooglets-witchcap": "Wooglet's Witchcap",
    "mu-phu-thuy-wooglet": "Mũ Phù Thủy Wooglet",
    "wits-end": "Wit's End",
    "dao-tim": "Đao Tím",
    "frost-queens-claim": "Frost Queen's Claim",
    "yeu-sach-cua-bang-hau": "Yêu Sách của Băng Hậu",
    "rapid-firecannon": "Rapid Firecannon",
    "dai-bac-lien-thanh": "Đại Bác Liên Thanh",
    "nomads-medallion": "Nomad's Medallion",
    "me-day-nomad": "Mề Đay Nomad",
    "targons-brace": "Targon's Brace",
    "vong-tay-targon": "Vòng Tay Targon",
    "frostfang": "Frostfang",
    "nanh-bang": "Nanh Băng",
    "lich-bane": "Lich Bane",
    "song-kiem-tai-uong": "Song Kiếm Tai Ương",
    "stinger": "Stinger",
    "kiem-chich": "Kiếm Chích",
    "banshees-veil": "Banshee's Veil",
    "day-chuyen-chu-thap": "Dây Chuyền Chữ Thập",
    "lord-van-damms-pillager": "Lord Van Damm's Pillager",
    "chuy-gai-lanh-chua-van-damm": "Chùy Gai Lãnh Chúa Van Damm",
    "aegis-of-the-legion": "Aegis of the Legion",
    "la-chan-quan-doan": "Lá Chắn Quân Đoàn",
    "redemption": "Redemption",
    "day-chuyen-chuoc-toi": "Dây Chuyền Chuộc Tội",
    "fiendish-codex": "Fiendish Codex",
    "sach-quy": "Sách Quỷ",
    "knights-vow": "Knight's Vow",
    "loi-the-hiep-si": "Lời Thề Hiệp Sĩ",
    "frozen-heart": "Frozen Heart",
    "tim-bang": "Tim Băng",
    "mercurys-treads": "Mercury's Treads",
    "giay-thuy-ngan": "Giày Thủy Ngân",
    "guardians-orb": "Guardian's Orb",
    "bang-cau": "Băng Cầu",
    "aether-wisp": "Aether Wisp",
    "linh-hon-lac-long": "Linh Hồn Lạc Lõng",
    "forbidden-idol": "Forbidden Idol",
    "di-vat-tai-uong": "Dị Vật Tai Ương",
    "nashors-tooth": "Nashor's Tooth",
    "nanh-nashor": "Nanh Nashor",
    "rylais-crystal-scepter": "Rylai's Crystal Scepter",
    "truong-pha-le-rylai": "Trượng Pha Lê Rylai",
    "boots-of-mobility": "Boots of Mobility",
    "giay-co-dong": "Giày Cơ Động",
    "wicked-hatchet": "Wicked Hatchet",
    "riu-doc": "Rìu Độc",
    "executioners-calling": "Executioner's Calling",
    "guom-do-te": "Gươm Đồ Tể",
    "guinsoos-rageblade": "Guinsoo's Rageblade",
    "cuong-dao-guinsoo": "Cuồng Đao Guinsoo",
    "caulfields-warhammer": "Caulfield's Warhammer",
    "bua-chien-caufield": "Búa Chiến Caufield",
    "serrated-dirk": "Serrated Dirk",
    "dao-hung-tan": "Dao Hung Tàn",
    "void-staff": "Void Staff",
    "truong-hu-vo": "Trượng Hư Vô",
    "haunting-guise": "Haunting Guise",
    "mat-na-ma-am": "Mặt Nạ Ma Ám",
    "dervish-blade": "Dervish Blade",
    "guom-tu-si": "Gươm Tu Sĩ",
    "mercurial-scimitar": "Mercurial Scimitar",
    "dao-thuy-ngan": "Đao Thủy Ngân",
    "quicksilver-sash": "Quicksilver Sash",
    "khan-giai-thuat": "Khăn Giải Thuật",
    "youmuus-ghostblade": "Youmuu's Ghostblade",
    "kiem-ma-youmuu": "Kiếm Ma Youmuu",
    "randuins-omen": "Randuin's Omen",
    "khien-bang-randuin": "Khiên Băng Randuin",
    "bilgewater-cutlass": "Bilgewater Cutlass",
    "kiem-hai-tac": "Kiếm Hải Tặc",
    "hextech-revolver": "Hextech Revolver",
    "sung-hextech": "Súng Hextech",
    "hextech-gunblade": "Hextech Gunblade",
    "kiem-sung-hextech": "Kiếm Súng Hextech",
    "duskblade-of-draktharr": "Duskblade of Draktharr",
    "da-kiem-draktharr": "Dạ Kiếm Draktharr",
    "liandrys-torment": "Liandry's Torment",
    "mat-na-doa-day-liandry": "Mặt Nạ Đọa Đầy Liandry",
    "hextech-protobelt01": "Hextech Protobelt-01",
    "dai-lung-hextech": "Đai Lưng Hextech",
    "blade-of-the-ruined-king": "Blade of the Ruined King",
    "guom-cua-vua-vo-danh": "Gươm Của Vua Vô Danh",
    "hexdrinker": "Hexdrinker",
    "kiem-rang-cua": "Kiếm Răng Cưa",
    "maw-of-malmortius": "Maw of Malmortius",
    "chuy-gai-malmortius": "Chùy Gai Malmortius",
    "zhonyas-hourglass": "Zhonya's Hourglass",
    "dong-ho-cat-zhonya": "Đồng Hồ Cát Zhonya",
    "ionian-boots-of-lucidity": "Ionian Boots of Lucidity",
    "giay-khai-sang-ionia": "Giày Khai Sáng Ionia",
    "morellonomicon": "Morellonomicon",
    "quy-thu-morello": "Quỷ Thư Morello",
    "moonflair-spellblade": "Moonflair Spellblade",
    "nguyet-kiem": "Nguyệt Kiếm",
    "athenes-unholy-grail": "Athene's Unholy Grail",
    "coc-quy-athene": "Cốc Quỷ Athene",
    "sanguine-blade": "Sanguine Blade",
    "huyet-dao": "Huyết Đao",
    "guardians-hammer": "Guardian's Hammer",
    "bua-bach-kim": "Búa Bạch Kim",
    "the-lightbringer": "The Lightbringer",
    "cung-anh-sang": "Cung Ánh Sáng",
    "arcane-sweeper": "Arcane Sweeper",
    "may-quet-hextech": "Máy Quét Hextech",
    "locket-of-the-iron-solari": "Locket of the Iron Solari",
    "day-chuyen-iron-solari": "Dây Chuyền Iron Solari",
    "seekers-armguard": "Seeker's Armguard",
    "giap-tay-seeker": "Giáp Tay Seeker",
    "the-hex-core-mk1": "The Hex Core mk-1",
    "loi-cong-nghe-mk-1": "Lõi Công Nghệ mk-1",
    "the-hex-core-mk2": "The Hex Core mk-2",
    "loi-cong-nghe-mk-2": "Lõi Công Nghệ mk-2",
    "perfect-hex-core": "Perfect Hex Core",
    "loi-cong-nghe-hoan-hao": "Lõi Công Nghệ Hoàn Hảo",
    "prototype-hex-core": "Prototype Hex Core",
    "loi-cong-nghe-nguyen-ban": "Lõi Công Nghệ Nguyên Bản",
    "spectres-cowl": "Spectre's Cowl",
    "ao-choang-am-anh": "Áo Choàng Ám Ảnh",
    "mikaels-crucible": "Mikael's Crucible",
    "hom-bao-ho-cua-mikael": "Hòm Bảo Hộ của Mikael",
    "poachers-dirk": "Poacher's Dirk",
    "dao-dao-tac": "Dao Đạo Tặc",
    "ludens-echo": "Luden's Echo",
    "vong-am-cua-luden": "Vọng Âm của Luden",
    "ancient-coin": "Ancient Coin",
    "dong-xu-co-dai": "Đồng Xu Cổ Đại",
    "relic-shield": "Relic Shield",
    "khien-co-vat": "Khiên Cổ Vật",
    "spellthiefs-edge": "Spellthief's Edge",
    "luoi-guom-doat-thuat": "Lưỡi Gươm Đoạt Thuật",
    "warding-totem-trinket": "Warding Totem (Trinket)",
    "mat-vat-to-phu-kien": "Mắt Vật Tổ (Phụ Kiện)",
    "sweeping-lens-trinket": "Sweeping Lens (Trinket)",
    "may-quet-phu-kien": "Máy Quét (Phụ Kiện)",
    "soul-anchor-trinket": "Soul Anchor (Trinket)",
    "neo-linh-hon-phu-kien": "Neo Linh Hồn (Phụ Kiện)",
    "greater-stealth-totem-trinket": "Greater Stealth Totem (Trinket)",
    "vat-to-xanh-toi-cao-phu-kien": "Vật Tổ Xanh Tối Cao (Phụ Kiện)",
    "greater-vision-totem-trinket": "Greater Vision Totem (Trinket)",
    "vat-to-tim-toi-cao-phu-kien": "Vật Tổ Tím Tối Cao (Phụ Kiện)",
    "farsight-alteration": "Farsight Alteration",
    "thau-kinh-bien-doi": "Thấu Kính Biến Đổi",
    "oracle-alteration": "Oracle Alteration",
    "oracle-bien-doi": "Oracle Biến Đổi",
    "face-of-the-mountain": "Face of the Mountain",
    "mat-na-son-thach": "Mặt Nạ Sơn Thạch",
    "golden-transcendence": "Golden Transcendence",
    "khoa-cang-hoang-kim": "Khóa Cảng Hoàng Kim",
    "golden-transcendence-disabled": "Golden Transcendence (Disabled)",
    "khoa-cang-hoang-kim-vo-hieu": "Khóa Cảng Hoàng Kim (Vô hiệu)",
    "seer-stone-trinket": "Seer Stone (Trinket)",
    "da-hien-triet-phu-kien": "Đá Hiền Triết (Phụ Kiện)",
    "ardent-censer": "Ardent Censer",
    "lu-huong-soi-suc": "Lư Hương Sôi Sục",
    "essence-reaver": "Essence Reaver",
    "luoi-hai-linh-hon": "Luỡi Hái Linh Hồn",
    "zzrot-portal": "Zz'Rot Portal",
    "thong-dao-zzrot": "Thông Đạo Zz'rot",
    "the-black-spear": "The Black Spear",
    "mui-giao-hac-am": "Mũi Giáo Hắc Ám",
    "siege-teleport": "Siege Teleport",
    "cong-dich-chuyen": "Cổng Dịch Chuyển",
    "siege-ballista": "Siege Ballista",
    "may-ban-cong-thanh": "Máy Bắn Công Thành",
    "tower-beam-of-ruination": "Tower: Beam of Ruination",
    "tru-tia-huy-diet": "Trụ: Tia Hủy Diệt",
    "port-pad": "Port Pad",
    "tham-dich-chuyen": "Thảm Dịch Chuyển",
    "tower-storm-bulwark": "Tower: Storm Bulwark",
    "tru-bao-lua-ma-thuat": "Trụ: Bão Lửa Ma Thuật",
    "nexus-siege-siege-weapon-slot": "Nexus Siege: Siege Weapon Slot",
    "nha-chinh-that-thu-khi-cu-cong-thanh": "Nhà Chính Thất Thủ: Khí Cụ Công Thành",
    "flash-zone": "Flash Zone",
    "vung-toc-bien": "Vùng Tốc Biến",
    "vanguard-banner": "Vanguard Banner",
    "co-lenh-tien-phong": "Cờ Lệnh Tiên Phong",
    "siege-refund": "Siege Refund",
    "hoan-tien-cong-thanh": "Hoàn tiền công thành",
    "entropy-field": "Entropy Field",
    "truong-entropy": "Trường Entropy",
    "shield-totem": "Shield Totem",
    "vat-to-che-chan": "Vật Tổ Che Chắn",
    "siege-teleport-inactive": "Siege Teleport (Inactive)",
    "cong-dich-chuyen-vo-hieu": "Cổng Dịch Chuyển (vô hiệu)",
    "siege-sight-warder": "Siege Sight Warder",
    "mat-quan-sat": "Mắt Quan Sát",
    "frosted-snax": "Frosted Snax",
    "banh-quy-dong-lanh": "Bánh Quy Đông Lạnh",
    "super-spicy-snax": "Super Spicy Snax",
    "banh-quy-cay-cap-7": "Bánh Quy Cay Cấp 7",
    "espresso-snax": "Espresso Snax",
    "banh-quy-ca-phe": "Bánh Quy Cà Phê",
    "rainbow-snax-party-pack": "Rainbow Snax Party Pack!",
    "hop-banh-quy-tiec-bay-mau": "Hộp Bánh Quy Tiệc Bảy Màu!",
    "stalkers-blade": "Stalker's Blade",
    "guom-truy-tung": "Gươm Truy Tung",
    "trackers-knife": "Tracker's Knife",
    "dao-san-bat": "Dao Săn Bắt",
    "skirmishers-sabre": "Skirmisher's Sabre",
    "dao-dung-do": "Đao Đụng Độ",
    "dead-mans-plate": "Dead Man's Plate",
    "giap-liet-si": "Giáp Liệt Sĩ",
    "titanic-hydra": "Titanic Hydra",
    "riu-dai-mang-xa-chi-can-chien": "Rìu Đại Mãng Xà (Chỉ Cận Chiến)",
    "bamis-cinder": "Bami's Cinder",
    "tan-tich-cua-bami": "Tàn Tích của Bami",
    "righteous-glory": "Righteous Glory",
    "vinh-quang-chan-chinh": "Vinh Quang Chân Chính",
    "crystalline-bracer": "Crystalline Bracer",
    "vong-tay-pha-le": "Vòng Tay Pha Lê",
    "lost-chapter": "Lost Chapter",
    "bi-chuong-that-truyen": "Bí Chương Thất Truyền",
    "deaths-dance": "Death's Dance",
    "vu-dieu-tu-than": "Vũ Điệu Tử Thần",
    "edge-of-night": "Edge of Night",
    "ao-choang-bong-toi": "Áo Choàng Bóng Tối",
    "fire-at-will": "Fire at Will",
    "mua-bom-bao-dan": "Mưa Bom Bão Đạn",
    "deaths-daughter": "Death's Daughter",
    "hau-due-tu-than": "Hậu Duệ Tử Thần",
    "raise-morale": "Raise Morale",
    "hao-khi-dang-cao": "Hào Khí Dâng Cao",
    "barrier": "Barrier",
    "la-chan": "Lá Chắn",
    "cleanse": "Cleanse",
    "thanh-tay": "Thanh Tẩy",
    "ignite": "Ignite",
    "thieu-dot": "Thiêu Đốt",
    "exhaust": "Exhaust",
    "kiet-suc": "Kiệt Sức",
    "flash": "Flash",
    "toc-bien": "Tốc Biến",
    "ghost": "Ghost",
    "toc-hanh": "Tốc Hành",
    "heal": "Heal",
    "hoi-mau": "Hồi Máu",
    "clarity": "Clarity",
    "minh-man": "Minh Mẫn",
    "to-the-king": "To the King!",
    "ho-gia": "Hộ Giá!",
    "poro-toss": "Poro Toss",
    "nem-poro": "Ném Poro",
    "smite": "Smite",
    "trung-phat": "Trừng Phạt",
    "mark": "Mark",
    "danh-dau": "Đánh Dấu",
    "teleport": "Teleport",
    "dich-chuyen": "Dịch Chuyển",
    "be-mau": "Bể Máu",
    "blood-well": "Blood Well",
    "khong-kich-hac-am": "Không Kích Hắc Ám",
    "dark-flight": "Dark Flight",
    "khat-mau-no-mau": "Khát Máu / Nợ Máu",
    "blood-thirst-blood-price": "Blood Thirst / Blood Price",
    "luoi-guom-doa-day": "Lưỡi Gươm Đọa Đày",
    "blades-of-torment": "Blades of Torment",
    "tuyet-diet": "Tuyệt Diệt",
    "massacre": "Massacre",
    "hut-hon": "Hút Hồn",
    "essence-theft": "Essence Theft",
    "qua-cau-ma-thuat": "Quả Cầu Ma Thuật",
    "orb-of-deception": "Orb of Deception",
    "lua-ho-li": "Lửa Hồ Li",
    "fox-fire": "Fox-Fire",
    "hon-gio": "Hôn Gió",
    "charm": "Charm",
    "phi-ho": "Phi Hồ",
    "spirit-rush": "Spirit Rush",
    "song-nghe": "Song Nghệ",
    "twin-disciplines": "Twin Disciplines",
    "dau-an-sat-thu": "Dấu Ấn Sát Thủ",
    "mark-of-the-assassin": "Mark of the Assassin",
    "bom-khoi": "Bom Khói",
    "twilight-shroud": "Twilight Shroud",
    "mua-liem": "Múa Liềm",
    "crescent-slash": "Crescent Slash",
    "vu-dieu-bong-dem": "Vũ Điệu Bóng Đêm",
    "shadow-dance": "Shadow Dance",
    "tieng-gam-chien-thang": "Tiếng Gầm Chiến Thắng",
    "triumphant-roar": "Triumphant Roar",
    "nghien-nat": "Nghiền Nát",
    "pulverize": "Pulverize",
    "bo-huc": "Bò Húc",
    "headbutt": "Headbutt",
    "giay-xeo": "Giày Xéo",
    "trample": "Trample",
    "bat-khuat": "Bất Khuất",
    "unbreakable-will": "Unbreakable Will",
    "cu-dap-nguyen-rua": "Cú Đập Nguyền Rủa",
    "cursed-touch": "Cursed Touch",
    "quang-dai-bang": "Quăng Dải Băng",
    "bandage-toss": "Bandage Toss",
    "tuyet-vong": "Tuyệt Vọng",
    "despair": "Despair",
    "gian-du": "Giận Dữ",
    "tantrum": "Tantrum",
    "loi-nguyen-cua-xac-uop-u-sau": "Lời Nguyền Của Xác Ướp U Sầu",
    "curse-of-the-sad-mummy": "Curse of the Sad Mummy",
    "tai-sinh": "Tái Sinh",
    "rebirth": "Rebirth",
    "qua-cau-bang": "Quả Cầu Băng",
    "flash-frost": "Flash Frost",
    "tuong-bang": "Tường Băng",
    "crystallize": "Crystallize",
    "te-cong": "Tê Cóng",
    "frostbite": "Frostbite",
    "bao-tuyet": "Bão Tuyết",
    "glacial-storm": "Glacial Storm",
    "hoa-cuong": "Hỏa Cuồng",
    "pyromania": "Pyromania",
    "hoa-cau": "Hỏa Cầu",
    "disintegrate": "Disintegrate",
    "thieu-chay": "Thiêu Cháy",
    "incinerate": "Incinerate",
    "khien-lua": "Khiên Lửa",
    "molten-shield": "Molten Shield",
    "trieu-hoi-tibbers": "Triệu Hồi: Tibbers",
    "summon:tibbers": "Summon: Tibbers",
    "bang-tien": "Băng Tiễn",
    "frost-shot": "Frost Shot",
    "chu-tam-tien": "Chú Tâm Tiễn",
    "rangers-focus": "Ranger's Focus",
    "tan-xa-tien": "Tán Xạ Tiễn",
    "volley": "Volley",
    "ung-tien": "Ưng Tiễn",
    "hawkshot": "Hawkshot",
    "dai-bang-tien": "Đại Băng Tiễn",
    "enchanted-crystal-arrow": "Enchanted Crystal Arrow",
    "trung-tam-vu-tru": "Trung Tâm Vũ Trụ",
    "center-of-the-universe": "Center of the Universe",
    "tinh-van-cau": "Tinh Vân Cầu",
    "starsurge": "Starsurge",
    "khai-mo-thien-ha": "Khai Mở Thiên Hà",
    "celestial-expansion": "Celestial Expansion",
    "du-hanh-khong-gian": "Du Hành Không Gian",
    "comet-of-legend": "Comet of Legend",
    "song-anh-sang": "Sóng Ánh Sáng",
    "voice-of-light": "Voice of Light",
    "di-san-cua-shurima": "Di Sản của Shurima",
    "shurimas-legacy": "Shurima's Legacy",
    "cat-can-quet": "Cát Càn Quét",
    "conquering-sands": "Conquering Sands",
    "troi-day": "Trỗi Dậy!",
    "arise": "Arise!",
    "cat-luu-dong": "Cát Lưu Động",
    "shifting-sands": "Shifting Sands",
    "phan-chia-thien-ha": "Phân Chia Thiên Hạ",
    "emperors-divide": "Emperor's Divide",
    "the-gioi-mau-nhiem": "Thế Giới Mầu Nhiệm",
    "travelers-call": "Traveler's Call",
    "mat-xich-khong-gian": "Mắt Xích Không Gian",
    "cosmic-binding": "Cosmic Binding",
    "dien-an-lac": "Điện An Lạc",
    "caretakers-shrine": "Caretaker's Shrine",
    "hanh-trinh-ki-dieu": "Hành Trình Kì Diệu",
    "magical-journey": "Magical Journey",
    "thien-menh-kha-bien": "Thiên Mệnh Khả Biến",
    "tempered-fate": "Tempered Fate",
    "la-chan-nang-luong": "Lá Chắn Năng Lượng",
    "mana-barrier": "Mana Barrier",
    "ban-tay-hoa-tien": "Bàn Tay Hỏa Tiễn",
    "rocket-grab": "Rocket Grab",
    "tang-toc": "Tăng Tốc",
    "overdrive": "Overdrive",
    "dam-moc": "Đấm Móc",
    "power-fist": "Power Fist",
    "truong-dien-tu": "Trường Điện Từ",
    "static-field": "Static Field",
    "bong": "Bỏng",
    "blaze": "Blaze",
    "vet-lua": "Vệt Lửa",
    "sear": "Sear",
    "cot-lua": "Cột Lửa",
    "pillar-of-flame": "Pillar of Flame",
    "bung-chay": "Bùng Cháy",
    "conflagration": "Conflagration",
    "bao-lua": "Bão Lửa",
    "pyroclasm": "Pyroclasm",
    "danh-ngat-ngu": "Đánh Ngất Ngư",
    "concussive-blows": "Concussive Blows",
    "tuyet-te-tai": "Tuyết Tê Tái",
    "winters-bite": "Winter's Bite",
    "nap-sau-ta": "Nấp Sau Ta",
    "stand-behind-me": "Stand Behind Me",
    "toi-kien-cuong": "Tối Kiên Cường",
    "unbreakable": "Unbreakable",
    "bang-dia-chan": "Băng Địa Chấn",
    "glacial-fissure": "Glacial Fissure",
    "thien-xa": "Thiện Xạ",
    "headshot": "Headshot",
    "ban-xuyen-tao": "Bắn Xuyên Táo",
    "piltover-peacemaker": "Piltover Peacemaker",
    "bay-yordle": "Bẫy Yordle",
    "yordle-snap-trap": "Yordle Snap Trap",
    "luoi90": "Lưới 90",
    "90-caliber-net": "90 Caliber Net",
    "bach-phat-bach-trung": "Bách Phát Bách Trúng",
    "ace-in-the-hole": "Ace in the Hole",
    "than-toc-mang-xa": "Thần Tốc Mãng Xà",
    "serpentine-grace": "Serpentine Grace",
    "vu-no-doc-hai": "Vụ Nổ Độc Hại",
    "noxious-blast": "Noxious Blast",
    "chuong-khi": "Chướng Khí",
    "miasma": "Miasma",
    "nanh-doc": "Nanh Độc",
    "twin-fang": "Twin Fang",
    "cai-nhin-hoa-da": "Cái Nhìn Hóa Đá",
    "petrifying-gaze": "Petrifying Gaze",
    "thu-an-thit": "Thú Ăn Thịt",
    "carnivore": "Carnivore",
    "ran-nut": "Rạn Nứt",
    "rupture": "Rupture",
    "tieng-gam-hoang-da": "Tiếng Gầm Hoang Dã",
    "feral-scream": "Feral Scream",
    "phong-gai": "Phóng Gai",
    "vorpal-spikes": "Vorpal Spikes",
    "xoi-tai": "Xơi Tái",
    "feast": "Feast",
    "dan-hextech": "Đạn Hextech",
    "hextech-munitions": "Hextech Munitions",
    "bom-phot-pho": "Bom Phốt-pho",
    "phosphorus-bomb": "Phosphorus Bomb",
    "tham-lua": "Thảm Lửa",
    "valkyrie": "Valkyrie",
    "sung-may": "Súng Máy",
    "gatling-gun": "Gatling Gun",
    "ten-lua-dinh-huong": "Tên Lửa Định Hướng",
    "missile-barrage": "Missile Barrage",
    "xuat-huyet": "Xuất Huyết",
    "hemorrhage": "Hemorrhage",
    "tan-sat": "Tàn Sát",
    "decimate": "Decimate",
    "danh-thot": "Đánh Thọt",
    "crippling-strike": "Crippling Strike",
    "bat-giu": "Bắt Giữ",
    "apprehend": "Apprehend",
    "may-chem-noxus": "Máy Chém Noxus",
    "noxian-guillotine": "Noxian Guillotine",
    "guom-anh-trang": "Gươm Ánh Trăng",
    "moonsilver-blade": "Moonsilver Blade",
    "trang-luoi-liem": "Trăng Lưỡi Liềm",
    "crescent-strike": "Crescent Strike",
    "thac-bac": "Thác Bạc",
    "pale-cascade": "Pale Cascade",
    "trang-mo": "Trăng Mờ",
    "moonfall": "Moonfall",
    "trang-non": "Trăng Non",
    "lunar-rush": "Lunar Rush",
    "lien-minh-draven": "Liên Minh Draven",
    "league-of-draven": "League of Draven",
    "riu-xoay": "Rìu Xoay",
    "spinning-axe": "Spinning Axe",
    "xung-huyet": "Xung Huyết",
    "blood-rush": "Blood Rush",
    "dat-ra": "Dạt Ra",
    "stand-aside": "Stand Aside",
    "loc-xoay-tu-vong": "Lốc Xoáy Tử Vong",
    "whirling-death": "Whirling Death",
    "hooc-mon-hung-phan": "Hooc-môn Hưng Phấn",
    "adrenaline-rush": "Adrenaline Rush",
    "dao-phay-nhiem-khuan": "Dao Phay Nhiễm Khuẩn",
    "infected-cleaver": "Infected Cleaver",
    "noi-dau-bong-chay": "Nỗi Đau Bỏng Cháy",
    "burning-agony": "Burning Agony",
    "cuong-bao": "Cuồng Bạo",
    "masochism": "Masochism",
    "mau-dien": "Máu Điên",
    "sadism": "Sadism",
    "dong-co-z-cong-huong": "Động Cơ Z Cộng Hưởng",
    "z-drive-resonance": "Z-Drive Resonance",
    "day-cot-thoi-gian": "Dây Cót Thời Gian",
    "timewinder": "Timewinder",
    "luong-gioi-dong-quy": "Lưỡng Giới Đồng Quy",
    "parallel-convergence": "Parallel Convergence",
    "bien-chuyen-pha": "Biến Chuyển Pha",
    "phase-dive": "Phase Dive",
    "dot-pha-thoi-gian": "Đột Phá Thời Gian",
    "chronobreak": "Chronobreak",
    "nu-hoang-nhen-nhen": "Nữ Hoàng Nhền Nhện",
    "spider-queen": "Spider Queen",
    "phun-doc-can-doc": "Phun Độc / Cắn Độc",
    "neurotoxin-venomous-bite": "Neurotoxin / Venomous Bite",
    "nhen-nhen-con-can-xe": "Nhền Nhện Con / Cắn Xé",
    "volatile-spiderling-skittering-frenzy": "Volatile Spiderling / Skittering Frenzy",
    "ken-nhen-danh-du": "Kén Nhện / Đánh Đu",
    "cocoon-rappel": "Cocoon / Rappel",
    "nhen-chua": "Nhện Chúa",
    "spider-form": "Spider Form",
    "vu-dieu-bong-toi": "Vũ Điệu Bóng Tối",
    "shadow-walk": "Shadow Walk",
    "gai-cam-han": "Gai Căm Hận",
    "hate-spike": "Hate Spike",
    "bong-dem-cuong-loan": "Bóng Đêm Cuồng Loạn",
    "dark-frenzy": "Dark Frenzy",
    "pha-hoai": "Phá Hoại",
    "ravage": "Ravage",
    "thong-kho": "Thống Khổ",
    "agonys-embrace": "Agony's Embrace",
    "phap-luc-gia-tang": "Pháp Lực Gia Tăng",
    "rising-spell-force": "Rising Spell Force",
    "phat-ban-than-bi": "Phát Bắn Thần Bí",
    "mystic-shot": "Mystic Shot",
    "tinh-hoa-tuon-chay": "Tinh Hoa Tuôn Chảy",
    "essence-flux": "Essence Flux",
    "dich-chuyen-co-hoc": "Dịch Chuyển Cổ Học",
    "arcane-shift": "Arcane Shift",
    "cung-anh-sang": "Cung Ánh Sáng",
    "trueshot-barrage": "Trueshot Barrage",
    "kinh-hoang": "Kinh Hoàng",
    "dread": "Dread",
    "khiep-hai": "Khiếp Hãi",
    "terrify": "Terrify",
    "hut-mau": "Hút Máu",
    "drain": "Drain",
    "con-gio-den": "Cơn Gió Đen",
    "dark-wind": "Dark Wind",
    "bao-qua": "Bão Quạ",
    "crowstorm": "Crowstorm",
    "vu-dieu-kiem-su": "Vũ Điệu Kiếm Sư",
    "duelists-dance": "Duelist's Dance",
    "lao-toi": "Lao Tới",
    "lunge": "Lunge",
    "phan-don": "Phản Đòn",
    "riposte": "Riposte",
    "nhat-kiem-nhi-dung": "Nhất Kiếm Nhị Dụng",
    "bladework": "Bladework",
    "dai-thu-thach": "Đại Thử Thách",
    "grand-challenge": "Grand Challenge",
    "chien-binh-lanh-loi": "Chiến Binh Lanh Lợi",
    "nimble-fighter": "Nimble Fighter",
    "dam-lao": "Đâm Lao",
    "urchin-strike": "Urchin Strike",
    "dinh-ba-hai-thach": "Đinh Ba Hải Thạch",
    "seastone-trident": "Seastone Trident",
    "tung-tang-nhay-mua": "Tung Tăng / Nhảy Múa",
    "playful-trickster": "Playful / Trickster",
    "trieu-hoi-thuy-quai": "Triệu Hồi Thủy Quái",
    "chum-the-waters": "Chum the Waters",
    "lop-da-co-ngu": "Lớp Da Cổ Ngữ",
    "runic-skin": "Runic Skin",
    "don-trung-phat": "Đòn Trừng Phạt",
    "resolute-smite": "Resolute Smite",
    "ma-doi-bao-ho": "Ma Dơi Bảo Hộ",
    "bulwark": "Bulwark",
    "ngon-gio-chinh-truc": "Ngọn Gió Chính Trực",
    "righteous-gust": "Righteous Gust",
    "su-bao-thu-cua-durand": "Sự Báo Thù Của Durand",
    "idol-of-durand": "Idol of Durand",
    "thu-lua": "Thử Lửa",
    "trial-by-fire": "Trial by Fire",
    "dam-phan": "Đàm Phán",
    "parrrley": "Parrrley",
    "bo-sung-vitamin": "Bổ Sung Vitamin",
    "remove-scurvy": "Remove Scurvy",
    "thung-thuoc-sung": "Thùng Thuốc Súng",
    "powder-keg": "Powder Keg",
    "mua-dai-bac": "Mưa Đại Bác",
    "cannon-barrage": "Cannon Barrage",
    "ben-bi": "Bền Bỉ",
    "perseverance": "Perseverance",
    "don-quyet-dinh": "Đòn Quyết Định",
    "decisive-strike": "Decisive Strike",
    "long-dung-cam": "Lòng Dũng Cảm",
    "courage": "Courage",
    "phan-quyet": "Phán Quyết",
    "judgment": "Judgment",
    "cong-li-demacia": "Công Lí Demacia",
    "demacian-justice": "Demacian Justice",
    "dot-bien-gien": "Đột Biến Gien",
    "rage-gene": "Rage Gene",
    "nem-boomerang-nem-da": "Ném Boomerang / Ném Đá",
    "boomerang-throw-boulder-toss": "Boomerang Throw / Boulder Toss",
    "qua-khich-dap-pha": "Quá Khích / Đập Phá",
    "hyper-wallop": "Hyper / Wallop",
    "nhun-nhay-nghien-nat": "Nhún Nhảy / Nghiền Nát",
    "hop-crunch": "Hop / Crunch",
    "gio-khuyen-mai": "Giờ Khuyến Mãi",
    "happy-hour": "Happy Hour",
    "lan-thung-ruou": "Lăn Thùng Rượu",
    "barrel-roll": "Barrel Roll",
    "say-qua-hoa-cuong": "Say Quá Hóa Cuồng",
    "drunken-rage": "Drunken Rage",
    "lay-thit-de-nguoi": "Lấy Thịt Đè Người",
    "body-slam": "Body Slam",
    "thung-ruou-no": "Thùng Rươu Nổ",
    "explosive-cask": "Explosive Cask",
    "van-menh-thay-doi": "Vận Mệnh Thay Đổi",
    "new-destiny": "New Destiny",
    "dan-xuyen-muc-tieu": "Đạn Xuyên Mục Tiêu",
    "end-of-the-line": "End of the Line",
    "bom-mu": "Bom Mù",
    "smoke-screen": "Smoke Screen",
    "rut-sung-nhanh": "Rút Súng Nhanh",
    "quickdraw": "Quickdraw",
    "dan-no-than-cong": "Đạn Nổ Thần Công",
    "collateral-damage": "Collateral Damage",
    "duong-ra-tran": "Đường Ra Trận",
    "warpath": "Warpath",
    "can-quet": "Càn Quét",
    "rampage": "Rampage",
    "nhiep-hon-tran": "Nhiếp Hồn Trận",
    "spirit-of-dread": "Spirit of Dread",
    "vo-ngua-huy-diet": "Vó Ngựa Hủy Diệt",
    "devastating-charge": "Devastating Charge",
    "bong-ma-ki-si": "Bóng Ma Kị Sĩ",
    "onslaught-of-shadows": "Onslaught of Shadows",
    "ma-phap-co-gioi": "Ma Pháp Cơ Giới",
    "techmaturgical-repair-bots": "Techmaturgical Repair Bots",
    "u-sung-tan-tien-h28-g": "Ụ Súng Tân Tiến H-28G",
    "h28-g-evolution-turret": "H-28G Evolution Turret",
    "ten-lua-hextech-co-nho": "Tên Lửa Hextech Cỡ Nhỏ",
    "hextech-micro-rockets": "Hextech Micro-Rockets",
    "luu-dan-bao-dien-tu-ch2": "Lựu Đạn Bão Điện Tử CH-2",
    "ch2-electron-storm-grenade": "CH-2 Electron Storm Grenade",
    "nang-cap": "NÂNG CẤP!!!",
    "upgrade": "UPGRADE!!!",
    "tien-tri-thuong-than": "Tiên Tri Thượng Thần",
    "prophet-of-an-elder-god": "Prophet of an Elder God",
    "xuc-tu-tan-pha": "Xúc Tu Tàn Phá",
    "tentacle-smash": "Tentacle Smash",
    "loi-ran-khac-nghiet": "Lời Răn Khắc Nghiệt",
    "harsh-lesson": "Harsh Lesson",
    "thu-thach-linh-hon": "Thử Thách Linh Hồn",
    "test-of-spirit": "Test of Spirit",
    "buoc-nhay-niem-tin": "Bước Nhảy Niềm Tin",
    "leap-of-faith": "Leap of Faith",
    "tinh-than-ionia": "Tinh Thần Ionia",
    "ionian-fervor": "Ionian Fervor",
    "dam-kiem": "Đâm Kiếm",
    "bladesurge": "Bladesurge",
    "kiem-thuat-hiten": "Kiếm Thuật Hiten",
    "hiten-style": "Hiten Style",
    "nhat-chem-can-bang": "Nhát Chém Cân Bằng",
    "equilibrium-strike": "Equilibrium Strike",
    "luoi-kiem-uu-viet": "Lưỡi Kiếm Ưu Việt",
    "transcendent-blades": "Transcendent Blades",
    "nguoi-ban-cua-rung-gia": "Người Bạn Của Rừng Già",
    "friend-of-the-forest": "Friend of the Forest",
    "re-rac-roi": "Rễ Rắc Rối",
    "rootcaller": "Rootcaller",
    "kien-tao-bui": "Kiến Tạo Bụi",
    "brushmaker": "Brushmaker",
    "hat-hu-hong": "Hạt Hư Hỏng",
    "triggerseed": "Triggerseed",
    "daisy": "Daisy!",
    "thuan-gio": "Thuận Gió",
    "tailwind": "Tailwind",
    "gio-loc": "Gió Lốc",
    "howling-gale": "Howling Gale",
    "gio-tay": "Gió Tây",
    "zephyr": "Zephyr",
    "mat-bao": "Mắt Bão",
    "eye-of-the-storm": "Eye Of The Storm",
    "gio-mua": "Gió Mùa",
    "monsoon": "Monsoon",
    "thuong-thuat": "Thương Thuật",
    "martial-cadence": "Martial Cadence",
    "giang-long-kich": "Giáng Long Kích",
    "dragon-strike": "Dragon Strike",
    "hoang-kim-giap": "Hoàng Kim Giáp",
    "golden-aegis": "Golden Aegis",
    "hoang-ki-demacia": "Hoàng Kì Demacia",
    "demacian-standard": "Demacian Standard",
    "dai-dia-chan": "Đại Địa Chấn",
    "cataclysm": "Cataclysm",
    "khong-khoan-nhuong": "Không Khoan Nhượng",
    "relentless-assault": "Relentless Assault",
    "nhay-va-nen": "Nhảy Và Nện",
    "leap-strike": "Leap Strike",
    "van-suc": "Vận Sức",
    "empower": "Empower",
    "phan-cong": "Phản Công",
    "counter-strike": "Counter Strike",
    "suc-manh-bac-thay": "Sức Mạnh Bậc Thầy",
    "grandmasters-might": "Grandmaster's Might",
    "tu-dien-hextech": "Tụ Điện Hextech",
    "hextech-capacitor": "Hextech Capacitor",
    "chi-thien-cau-sam": "Chỉ Thiên! / Cầu Sấm",
    "to-the-skies-shock-blast": "To the Skies! / Shock Blast",
    "sam-chop-ren-vang-tich-tu": "Sấm Chớp Rền Vang / Tích Tụ",
    "lightning-field-hyper-charge": "Lightning Field / Hyper Charge",
    "loi-phat-cong-tang-toc": "Lôi Phạt / Cổng Tăng Tốc",
    "thundering-blow-acceleration-gate": "Thundering Blow / Acceleration Gate",
    "phao-thuy-ngan-bua-thuy-ngan": "Pháo Thủy Ngân / Búa Thủy Ngân",
    "mercury-cannon-mercury-hammer": "Mercury Cannon / Mercury Hammer",
    "loi-thi-tham": "Lời Thì Thầm",
    "whisper": "Whisper",
    "luu-dan-nhay-mua": "Lựu Đạn Nhảy Múa",
    "dancing-grenade": "Dancing Grenade",
    "net-ve-chet-choc": "Nét Vẽ Chết Chóc",
    "deadly-flourish": "Deadly Flourish",
    "cam-bay-nghe-thuat": "Cạm Bẫy Nghệ Thuật",
    "captive-audience": "Captive Audience",
    "san-khau-tu-than": "Sân Khấu Tử Thần",
    "curtain-call": "Curtain Call",
    "hung-phan": "Hưng Phấn!",
    "get-excited": "Get Excited!",
    "trao-hang-": "Tráo Hàng! ",
    "switcheroo": "Switcheroo!",
    "giat-ban-": "Giật Bắn! ",
    "zap": "Zap!",
    "luu-dan-ma-hoa-": "Lựu Đạn Ma Hỏa! ",
    "flame-chompers": "Flame Chompers!",
    "ten-lua-dan-dao-sieu-khung-khiep": "Tên Lửa Đạn Đạo Siêu Khủng Khiếp",
    "super-mega-death-rocket": "Super Mega Death Rocket!",
    "phong-thai-quan-nhan": "Phong Thái Quân Nhân",
    "martial-poise": "Martial Poise",
    "dam-xuyen": "Đâm Xuyên",
    "pierce": "Pierce",
    "hon-ma-do-tham": "Hồn Ma Do Thám",
    "sentinel": "Sentinel",
    "giay-vo": "Giày Vò",
    "rend": "Rend",
    "dinh-menh-vay-goi": "Định Mệnh Vẫy Gọi",
    "fates-call": "Fate's Call",
    "tu-hoa": "Tụ Hỏa",
    "gathering-fire": "Gathering Fire",
    "noi-hoa": "Nội Hỏa",
    "inner-flame": "Inner Flame",
    "chuyen-tam": "Chuyên Tâm",
    "focused-resolve": "Focused Resolve",
    "linh-giap": "Linh Giáp",
    "inspire": "Inspire",
    "kinh-mantra": "Kinh Mantra",
    "mantra": "Mantra",
    "vong-hon": "Vong Hồn",
    "death-defied": "Death Defied",
    "tan-pha": "Tàn Phá",
    "lay-waste": "Lay Waste",
    "buc-tuong-dau-don": "Bức Tường Đau Đớn",
    "wall-of-pain": "Wall of Pain",
    "o-ue": "Ô Uế",
    "defile": "Defile",
    "khuc-cau-hon": "Khúc Cầu Hồn",
    "requiem": "Requiem",
    "da-hu-khong": "Đá Hư Không",
    "void-stone": "Void Stone",
    "qua-cau-hu-khong": "Quả Cầu Hư Không",
    "null-sphere": "Null Sphere",
    "luoi-kiem-am-ti": "Lưỡi Kiếm Âm Ti",
    "nether-blade": "Nether Blade",
    "ap-suat-hu-khong": "Áp Suất Hư Không",
    "force-pulse": "Force Pulse",
    "hu-vo-bo-phap": "Hư Vô Bộ Pháp",
    "riftwalk": "Riftwalk",
    "tham-lam": "Tham Lam",
    "voracity": "Voracity",
    "phi-dao": "Phi Dao",
    "bouncing-blade": "Bouncing Blade",
    "tung-hung": "Tung Hứng",
    "preparation": "Preparation",
    "am-sat": "Ám Sát",
    "shunpo": "Shunpo",
    "bong-sen-tu-than": "Bông Sen Tử Thần",
    "death-lotus": "Death Lotus",
    "nhiet-huyet-than-thanh": "Nhiệt Huyết Thần Thánh",
    "holy-fervor": "Holy Fervor",
    "trung-phat": "Trừng Phạt",
    "reckoning": "Reckoning",
    "ban-phuoc": "Ban Phước",
    "divine-blessing": "Divine Blessing",
    "cong-li-thinh-no": "Công Lí Thịnh Nộ",
    "righteous-fury": "Righteous Fury",
    "bat-tu-ho-than": "Bất Tử Hộ Thân",
    "intervention": "Intervention",
    "dau-an-sam-set": "Dấu Ấn Sấm Sét",
    "mark-of-the-storm": "Mark of the Storm",
    "phi-tieu-set": "Phi Tiêu Sét",
    "thundering-shuriken": "Thundering Shuriken",
    "giat-set": "Giật Sét",
    "electrical-surge": "Electrical Surge",
    "toc-do-sam-set": "Tốc Độ Sấm Sét",
    "lightning-rush": "Lightning Rush",
    "bao-sam-set": "Bão Sấm Sét",
    "slicing-maelstrom": "Slicing Maelstrom",
    "hiem-hoa-tiem-tang": "Hiểm Họa Tiềm Tàng",
    "unseen-threat": "Unseen Threat",
    "nem-mui-so-hai": "Nếm Mùi Sợ Hãi",
    "taste-their-fear": "Taste Their Fear",
    "gai-hu-khong": "Gai Hư Không",
    "void-spike": "Void Spike",
    "nhay": "Nhảy",
    "leap": "Leap",
    "dot-kich-hu-khong": "Đột Kích Hư Không",
    "void-assault": "Void Assault",
    "dong-nguyen-an": "Đồng Nguyên Ấn",
    "mark-of-the-kindred": "Mark of the Kindred",
    "vu-dieu-xa-tien": "Vũ Điệu Xạ Tiễn",
    "dance-of-arrows": "Dance of Arrows",
    "soi-cuong-loan": "Sói Cuồng Loạn",
    "wolfs-frenzy": "Wolf's Frenzy",
    "so-hai-dang-trao": "Sợ Hãi Dâng Trào",
    "mounting-dread": "Mounting Dread",
    "cuu-cuu-sinh": "Cừu Cứu Sinh",
    "lambs-respite": "Lamb's Respite",
    "skaarl-than-lan-hen-nhat": "Skaarl Thằn Lằn Hèn Nhát",
    "skaarl,the-cowardly-lizard": "Skaarl, the Cowardly Lizard",
    "day-thung-bay-gau": "Dây Thừng Bẫy Gấu",
    "bear-trap-on-a-rope": "Bear Trap on a Rope",
    "khuynh-huong-bao-luc": "Khuynh Hướng Bạo Lực",
    "violent-tendencies": "Violent Tendencies",
    "cuoi-ngua-dau-thuong": "Cưỡi Ngựa Đấu Thương",
    "jousting": "Jousting",
    "xung-phooong": "Xung Phooong!!!",
    "chaaaaaaaarge": "Chaaaaaaaarge!!!",
    "bat-ngo-tu-icathia": "Bất Ngờ Từ Icathia",
    "icathian-surprise": "Icathian Surprise",
    "phun-axit": "Phun Axít",
    "caustic-spittle": "Caustic Spittle",
    "cao-xa-ma-phap": "Cao Xạ Ma Pháp",
    "bio-arcane-barrage": "Bio-Arcane Barrage",
    "dung-dich-hu-khong": "Dung Dịch Hư Không",
    "void-ooze": "Void Ooze",
    "phao-sinh-hoc": "Pháo Sinh Học",
    "living-artillery": "Living Artillery",
    "an-ac-y": "Ấn Ác Ý",
    "sigil-of-malice": "Sigil of Malice",
    "qua-cau-tan-vo": "Quả Cầu Tan Vỡ",
    "shatter-orb": "Shatter Orb",
    "bien-anh": "Biến Ảnh",
    "distortion": "Distortion",
    "soi-xich-sieu-pham": "Sợi Xích Siêu Phàm",
    "ethereal-chains": "Ethereal Chains",
    "mo-phong": "Mô Phỏng",
    "mimic": "Mimic",
    "loan-da": "Loạn Đả",
    "flurry": "Flurry",
    "song-am-vo-anh-cuoc": "Sóng Âm / Vô Ảnh Cước",
    "sonic-wave-resonating-strike": "Sonic Wave / Resonating Strike",
    "ho-the-kien-dinh": "Hộ Thể / Kiên Định",
    "safeguard-iron-will": "Safeguard / Iron Will",
    "dia-chan-du-chan": "Địa Chấn / Dư Chấn",
    "tempest-cripple": "Tempest / Cripple",
    "no-long-cuoc": "Nộ Long Cước",
    "dragons-rage": "Dragon's Rage",
    "anh-sang-mat-troi": "Ánh Sáng Mặt Trời",
    "sunlight": "Sunlight",
    "khien-mat-troi": "Khiên Mặt Trời",
    "shield-of-daybreak": "Shield of Daybreak",
    "nhat-thuc": "Nhật Thực",
    "eclipse": "Eclipse",
    "thien-dinh-kiem": "Thiên Đỉnh Kiếm",
    "zenith-blade": "Zenith Blade",
    "thai-duong-ha-san": "Thái Dương Hạ San",
    "solar-flare": "Solar Flare",
    "bang-yeu": "Băng Yêu",
    "iceborn": "Iceborn",
    "manh-bang": "Mảnh Băng",
    "ice-shard": "Ice Shard",
    "vong-tron-lanh-gia": "Vòng Tròn Lạnh Giá",
    "ring-of-frost": "Ring of Frost",
    "con-duong-bang-gia": "Con Đường Băng Giá",
    "glacial-path": "Glacial Path",
    "ham-mo-han-bang": "Hầm Mộ Hàn Băng",
    "frozen-tomb": "Frozen Tomb",
    "xa-thu-anh-sang": "Xạ Thủ Ánh Sáng",
    "lightslinger": "Lightslinger",
    "tia-sang-xuyen-thau": "Tia Sáng Xuyên Thấu",
    "piercing-light": "Piercing Light",
    "tia-sang-ruc-chay": "Tia Sáng Rực Cháy",
    "ardent-blaze": "Ardent Blaze",
    "truy-cung-diet-tan": "Truy Cùng Diệt Tận",
    "relentless-pursuit": "Relentless Pursuit",
    "thanh-trung": "Thanh Trừng",
    "the-culling": "The Culling",
    "ban-dong-hanh-pix": "Bạn Đồng Hành Pix",
    "pix,faerie-companion": "Pix, Faerie Companion",
    "ngon-thuong-anh-sang": "Ngọn Thương Ánh Sáng",
    "glitterlance": "Glitterlance",
    "bien-hoa": "Biến Hóa",
    "whimsy": "Whimsy",
    "giup-nao-pix": "Giúp Nào Pix!",
    "help,pix": "Help, Pix!",
    "khong-lo-hoa": "Khổng Lồ Hóa",
    "wild-growth": "Wild Growth",
    "chop-lua-soi-roi": "Chớp Lửa Soi Rọi",
    "illumination": "Illumination",
    "khoa-anh-sang": "Khóa Ánh Sáng",
    "light-binding": "Light Binding",
    "lang-kinh-phong-ho": "Lăng Kính Phòng Hộ",
    "prismatic-barrier": "Prismatic Barrier",
    "qua-cau-anh-sang": "Quả Cầu Ánh Sáng",
    "lucent-singularity": "Lucent Singularity",
    "cau-vong-toi-thuong": "Cầu Vồng Tối Thượng",
    "final-spark": "Final Spark",
    "giap-hoa-cuong": "Giáp Hoa Cương",
    "granite-shield": "Granite Shield",
    "manh-vo-dia-chan": "Mảnh Vỡ Địa Chấn",
    "seismic-shard": "Seismic Shard",
    "nam-dam-dung-nham": "Nắm Đấm Dung Nham",
    "brutal-strikes": "Brutal Strikes",
    "dam-dat": "Dậm Đất",
    "ground-slam": "Ground Slam",
    "khong-the-can-pha": "Không Thể Cản Phá",
    "unstoppable-force": "Unstoppable Force",
    "chuyen-doi-hu-khong": "Chuyển Đổi Hư Không",
    "void-shift": "Void Shift",
    "tieng-goi-hu-khong": "Tiếng Gọi Hư Không",
    "call-of-the-void": "Call of the Void",
    "bay-bo-hu-khong": "Bầy Bọ Hư Không",
    "void-swarm": "Void Swarm",
    "am-anh-kinh-hoang": "Ám Ảnh Kinh Hoàng",
    "malefic-visions": "Malefic Visions",
    "am-ti-troi-buoc": "Âm Ti Trói Buộc",
    "nether-grasp": "Nether Grasp",
    "ma-phap-nhua-cay": "Ma Pháp Nhựa Cây",
    "sap-magic": "Sap Magic",
    "song-co-hoc": "Sóng Cổ Học",
    "arcane-smash": "Arcane Smash",
    "bui-cay-ma-thuat": "Bụi Cây Ma Thuật",
    "twisted-advance": "Twisted Advance",
    "nem-choi-non": "Ném Chồi Non",
    "sapling-toss": "Sapling Toss",
    "bao-la-thu-han": "Bão Lá Thù Hận",
    "vengeful-maelstrom": "Vengeful Maelstrom",
    "chem-doi": "Chém Đôi",
    "double-strike": "Double Strike",
    "tuyet-ki-alpha": "Tuyệt Kĩ Alpha",
    "alpha-strike": "Alpha Strike",
    "thien": "Thiền",
    "meditate": "Meditate",
    "vo-thuat-wuju": "Võ Thuật Wuju",
    "wuju-style": "Wuju Style",
    "chien-binh-son-cuoc": "Chiến Binh Sơn Cước",
    "highlander": "Highlander",
    "danh-yeu": "Đánh Yêu",
    "love-tap": "Love Tap",
    "ban-mot-duoc-hai": "Bắn Một Được Hai",
    "double-up": "Double Up",
    "sai-buoc": "Sải Bước",
    "strut": "Strut",
    "mua-dan": "Mưa Đạn",
    "make-it-rain": "Make It Rain",
    "bao-dan": "Bão Đạn",
    "bullet-time": "Bullet Time",
    "minh-dong-da-sat": "Mình Đồng Da Sắt",
    "stone-skin": "Stone Skin",
    "thiet-bang-ngan-can": "Thiết Bảng Ngàn Cân",
    "crushing-blow": "Crushing Blow",
    "chim-moi": "Chim Mồi",
    "decoy": "Decoy",
    "can-dau-van": "Cân Đẩu Vân",
    "nimbus-strike": "Nimbus Strike",
    "loc-xoay": "Lốc Xoáy",
    "cyclone": "Cyclone",
    "nguoi-sat": "Người Sắt",
    "iron-man": "Iron Man",
    "chuy-bay": "Chùy Bay",
    "mace-of-spades": "Mace of Spades",
    "giap-kim-loai": "Giáp Kim Loại",
    "harvesters-of-sorrow": "Harvesters of Sorrow",
    "suc-hut-huy-diet": "Sức Hút Hủy Diệt",
    "siphon-of-destruction": "Siphon of Destruction",
    "bat-hon": "Bắt Hồn",
    "children-of-the-grave": "Children of the Grave",
    "luc-hut-tam-linh": "Lực Hút Tâm Linh",
    "soul-siphon": "Soul Siphon",
    "khoa-bong-toi": "Khóa Bóng Tối",
    "dark-binding": "Dark Binding",
    "vung-dat-chet": "Vùng Đất Chết",
    "tormented-soil": "Tormented Soil",
    "khien-den": "Khiên Đen",
    "black-shield": "Black Shield",
    "troi-hon": "Trói Hồn",
    "soul-shackles": "Soul Shackles",
    "day-song": "Dậy Sóng",
    "surging-tides": "Surging Tides",
    "thuy-nguc": "Thủy Ngục",
    "aqua-prison": "Aqua Prison",
    "thuy-trieu": "Thủy Triều",
    "ebb-and-flow": "Ebb and Flow",
    "uoc-nguyen-tien-ca": "Ước Nguyện Tiên Cá",
    "tidecallers-blessing": "Tidecaller's Blessing",
    "song-than": "Sóng Thần",
    "tidal-wave": "Tidal Wave",
    "ke-nuot-chung-linh-hon": "Kẻ Nuốt Chửng Linh Hồn",
    "soul-eater": "Soul Eater",
    "quyen-truong-linh-hon": "Quyền Trượng Linh Hồn",
    "siphoning-strike": "Siphoning Strike",
    "lao-hoa": "Lão Hóa",
    "wither": "Wither",
    "lua-tam-linh": "Lửa Tâm Linh",
    "spirit-fire": "Spirit Fire",
    "con-cuong-no-sa-mac": "Cơn Cuồng Nộ Sa Mạc",
    "fury-of-the-sands": "Fury of the Sands",
    "mo-neo-ngan-can": "Mỏ Neo Ngàn Cân",
    "staggering-blow": "Staggering Blow",
    "phong-mo-neo": "Phóng Mỏ Neo",
    "dredge-line": "Dredge Line",
    "con-gian-cua-nguoi-khong-lo": "Cơn Giận Của Người Khổng Lồ",
    "titans-wrath": "Titan's Wrath",
    "thuy-trieu-du-doi": "Thủy Triều Dữ Dội",
    "riptide": "Riptide",
    "thuy-loi-tam-nhiet": "Thủy Lôi Tầm Nhiệt",
    "depth-charge": "Depth Charge",
    "rinh-rap": "Rình Rập",
    "prowl": "Prowl",
    "phong-lao-can-xe": "Phóng Lao / Cắn Xé",
    "javelin-toss-takedown": "Javelin Toss / Takedown",
    "bay-rap-vo": "Bẫy Rập / Vồ",
    "bushwhack-pounce": "Bushwhack / Pounce",
    "suc-manh-hoang-da-va": "Sức Mạnh Hoang Dã / Vả",
    "primal-surge-swipe": "Primal Surge / Swipe",
    "lot-bao": "Lốt Báo",
    "aspect-of-the-cougar": "Aspect Of The Cougar",
    "luoi-dao-bong-toi": "Lưỡi Dao Bóng Tối",
    "umbra-blades": "Umbra Blades",
    "hoang-hon-buong-xuong": "Hoàng Hôn Buông Xuống",
    "duskbringer": "Duskbringer",
    "bong-den-bao-phu": "Bóng Đen Bao Phủ",
    "shroud-of-darkness": "Shroud of Darkness",
    "noi-kinh-hoang-tot-do": "Nỗi Kinh Hoàng Tột Độ",
    "unspeakable-horror": "Unspeakable Horror",
    "hoang-tuong": "Hoang Tưởng",
    "paranoia": "Paranoia",
    "nhin-xa-trong-rong": "Nhìn Xa Trông Rộng",
    "visionary": "Visionary",
    "nuot-chung": "Nuốt Chửng",
    "consume": "Consume",
    "soi-mau": "Sôi Máu",
    "blood-boil": "Blood Boil",
    "cau-tuyet": "Cầu Tuyết",
    "ice-blast": "Ice Blast",
    "tuyet-dinh-bang-gia": "Tuyệt Đỉnh Băng Giá",
    "absolute-zero": "Absolute Zero",
    "dien-cuong": "Điên Cuồng",
    "berserker-rage": "Berserker Rage",
    "phong-riu": "Phóng rìu",
    "undertow": "Undertow",
    "riu-mau": "Rìu Máu",
    "vicious-strikes": "Vicious Strikes",
    "bo-cui": "Bổ Củi",
    "reckless-swing": "Reckless Swing",
    "tan-the-ragnarok": "Tận Thế Ragnarok",
    "ragnarok": "Ragnarok",
    "len-day-cot": "Lên Dây Cót",
    "clockwork-windup": "Clockwork Windup",
    "lenh-tan-cong": "Lệnh: Tấn Công",
    "command:attack": "Command: Attack",
    "lenh-phat-song": "Lệnh: Phát Sóng",
    "command:dissonance": "Command: Dissonance",
    "lenh-bao-ve": "Lệnh: Bảo Vệ",
    "command:protect": "Command: Protect",
    "lenh-song-am": "Lệnh: Sóng Âm",
    "command:shockwave": "Command: Shockwave",
    "che-chan": "Che Chắn",
    "aegis-protection": "Aegis Protection",
    "phong-lao": "Phóng Lao",
    "spear-shot": "Spear Shot",
    "zeonia-ho-menh": "Zeonia Hộ Mệnh",
    "aegis-of-zeonia": "Aegis of Zeonia",
    "cong-kich-vu-bao": "Công Kích Vũ Bão",
    "heartseeker-strike": "Heartseeker Strike",
    "troi-sap": "Trời Sập",
    "grand-skyfall": "Grand Skyfall",
    "su-gia-thep": "Sứ Giả Thép",
    "iron-ambassador": "Iron Ambassador",
    "bua-chan-dong": "Búa Chấn Động",
    "hammer-shock": "Hammer Shock",
    "khong-the-lay-chuyen": "Không Thể Lay Chuyển",
    "steadfast-presence": "Steadfast Presence",
    "xung-phong": "Xung Phong",
    "heroic-charge": "Heroic Charge",
    "su-gia-phan-quyet": "Sứ Giả Phán Quyết",
    "keepers-verdict": "Keeper's Verdict",
    "chim-san-moi": "Chim Săn Mồi",
    "harrier": "Harrier",
    "khong-kich": "Không Kích",
    "blinding-assault": "Blinding Assault",
    "ung-nhan": "Ưng Nhãn",
    "heightened-senses": "Heightened Senses",
    "dot-kich": "Đột Kích",
    "vault": "Vault",
    "di-qua-don-dich": "Đi Qua Đồn Địch",
    "behind-enemy-lines": "Behind Enemy Lines",
    "vo-gai": "Vỏ Gai",
    "spiked-shell": "Spiked Shell",
    "qua-cau-toc-do": "Quả Cầu Tốc Độ",
    "powerball": "Powerball",
    "the-thu": "Thế Thủ",
    "defensive-ball-curl": "Defensive Ball Curl",
    "khieu-khich": "Khiêu Khích",
    "puncturing-taunt": "Puncturing Taunt",
    "dong-dat": "Động Đất",
    "tremors": "Tremors",
    "con-thinh-no-cua-xersai": "Cơn Thịnh Nộ của Xer'Sai",
    "fury-of-the-xersai": "Fury of the Xer'Sai",
    "nu-hoang-phan-no-san-moi": "Nữ Hoàng Phẫn Nộ / Săn Mồi",
    "queens-wrath-prey-seeker": "Queen's Wrath / Prey Seeker",
    "don-tho-troi-len": "Độn Thổ / Trồi Lên",
    "burrow-un-burrow": "Burrow / Un-burrow",
    "ngom-ngoam-ngau-nghien-duong-ham": "Ngồm Ngoàm Ngấu Nghiến / Đường Hầm",
    "furious-bite-tunnel": "Furious Bite / Tunnel",
    "toc-hanh-hu-khong": "Tốc Hành Hư Không",
    "void-rush": "Void Rush",
    "de-che-cuong-no": "Đế Chế Cuồng Nộ",
    "reign-of-anger": "Reign of Anger",
    "vu-dieu-ca-sau": "Vũ Điệu Cá Sấu",
    "cull-the-meek": "Cull the Meek",
    "ke-san-moi-tan-nhan": "Kẻ Săn Mồi Tàn Nhẫn",
    "ruthless-predator": "Ruthless Predator",
    "cat-va-xat": "Cắt và Xắt",
    "slice-and-dice": "Slice and Dice",
    "than-ca-sau": "Thần Cá Sấu",
    "dominus": "Dominus",
    "thu-san-moi-lan-khuat": "Thú Săn Mồi Lẩn Khuất",
    "unseen-predator": "Unseen Predator",
    "tan-ac": "Tàn Ác",
    "savagery": "Savagery",
    "tieng-gam-chien-tran": "Tiếng Gầm Chiến Trận",
    "battle-roar": "Battle Roar",
    "cu-nem-bola": "Cú Ném Bola",
    "bola-strike": "Bola Strike",
    "khao-khat-san-moi": "Khao Khát Săn Mồi",
    "thrill-of-the-hunt": "Thrill of the Hunt",
    "kiem-co-ngu": "Kiếm Cổ Ngữ",
    "runic-blade": "Runic Blade",
    "tam-bo-kiem": "Tam Bộ Kiếm",
    "broken-wings": "Broken Wings",
    "kinh-luc": "Kình Lực",
    "ki-burst": "Ki Burst",
    "anh-dung": "Anh Dũng",
    "valor": "Valor",
    "luoi-kiem-luu-day": "Lưỡi Kiếm Lưu Đày",
    "blade-of-the-exile": "Blade of the Exile",
    "khong-lo-bai-rac": "Khổng Lồ Bãi Rác",
    "junkyard-titan": "Junkyard Titan",
    "sung-phun-lua": "Súng Phun Lửa",
    "flamespitter": "Flamespitter",
    "khien-phe-lieu": "Khiên Phế Liệu",
    "scrap-shield": "Scrap Shield",
    "lao-moc-dien": "Lao Móc Điện",
    "electro-harpoon": "Electro Harpoon",
    "mua-ten-lua": "Mưa Tên Lửa",
    "the-equalizer": "The Equalizer",
    "bac-thay-co-thuat": "Bậc Thầy Cổ Thuật",
    "arcane-mastery": "Arcane Mastery",
    "qua-tai": "Quá Tải",
    "overload": "Overload",
    "nguc-co-ngu": "Ngục Cổ Ngữ",
    "rune-prison": "Rune Prison",
    "dong-chay-ma-phap": "Dòng Chảy Ma Pháp",
    "spell-flux": "Spell Flux",
    "vong-xoay-khong-gian": "Vòng Xoáy Không Gian",
    "realm-warp": "Realm Warp",
    "bang": "Băng",
    "frost": "Frost",
    "dot-kich-bang-gia": "Đột Kích Băng Giá",
    "arctic-assault": "Arctic Assault",
    "cu-vut-gio-phuong-bac": "Cú Vụt Gió Phương Bắc",
    "flail-of-the-northern-winds": "Flail of the Northern Winds",
    "bang-gia-vinh-cuu": "Băng Giá Vĩnh Cửu",
    "permafrost": "Permafrost",
    "nha-nguc-buot-gia": "Nhà Ngục Buốt Giá",
    "glacial-prison": "Glacial Prison",
    "dam-len": "Đâm Lén",
    "backstab": "Backstab",
    "lua-gat": "Lừa Gạt",
    "deceive": "Deceive",
    "hop-he-ma-quai": "Hộp Hề Ma Quái",
    "jack-in-the-box": "Jack In The Box",
    "dao-doc": "Dao Độc",
    "two-shiv-poison": "Two-Shiv Poison",
    "phan-than": "Phân Thân",
    "hallucinate": "Hallucinate",
    "la-chan-kiem-khi": "Lá Chắn Kiếm Khí",
    "ki-barrier": "Ki Barrier",
    "cong-kich-hoang-hon": "Công Kích Hoàng Hôn",
    "twilight-assault": "Twilight Assault",
    "bao-ho-linh-hon": "Bảo Hộ Linh Hồn",
    "spirits-refuge": "Spirit's Refuge",
    "vo-anh-bo": "Vô Ảnh Bộ",
    "shadow-dash": "Shadow Dash",
    "nhat-thong": "Nhất Thống",
    "stand-united": "Stand United",
    "cuong-no-long-nhan": "Cuồng Nộ Long Nhân",
    "fury-of-the-dragonborn": "Fury of the Dragonborn",
    "song-long-thu": "Song Long Thủ",
    "twin-bite": "Twin Bite",
    "ruc-chay": "Rực Cháy",
    "burnout": "Burnout",
    "hoi-tho-cua-rong": "Hơi Thở Của Rồng",
    "flame-breath": "Flame Breath",
    "hoa-rong": "Hóa Rồng",
    "dragons-descent": "Dragon's Descent",
    "giap-cuong-hoa": "Giáp Cường Hóa",
    "empowered-bulwark": "Empowered Bulwark",
    "phun-khoi-doc": "Phun Khói Độc",
    "poison-trail": "Poison Trail",
    "keo-sieu-dinh": "Keo Siêu Dính",
    "mega-adhesive": "Mega Adhesive",
    "hat": "Hất",
    "fling": "Fling",
    "thuoc-hoa-dien": "Thuốc Hóa Điên",
    "insanity-potion": "Insanity Potion",
    "vinh-quang-tu-si": "Vinh Quang Tử Sĩ",
    "glory-in-death": "Glory in Death",
    "cu-nen-tan-khoc": "Cú Nện Tàn Khốc",
    "decimating-smash": "Decimating Smash",
    "lo-luyen-hon": "Lò Luyện Hồn",
    "soul-furnace": "Soul Furnace",
    "sat-nhan-hong": "Sát Nhân Hống",
    "roar-of-the-slayer": "Roar of the Slayer",
    "bat-kha-khang-cu": "Bất Khả Kháng Cự",
    "unstoppable-onslaught": "Unstoppable Onslaught",
    "buoc-chan-uyen-chuyen": "Bước Chân Uyển Chuyển",
    "fleet-of-foot": "Fleet of Foot",
    "guom-boomerang": "Gươm Boomerang",
    "boomerang-blade": "Boomerang Blade",
    "nay-bat": "Nảy Bật",
    "ricochet": "Ricochet",
    "khien-chong-phep": "Khiên Chống Phép",
    "spell-shield": "Spell Shield",
    "san-duoi": "Săn Đuổi",
    "on-the-hunt": "On The Hunt",
    "thap-tinh-the": "Tháp Tinh Thể",
    "crystal-spires": "Crystal Spires",
    "nhat-chem-tinh-the": "Nhát Chém Tinh Thể",
    "crystal-slash": "Crystal Slash",
    "lop-vo-tinh-the": "Lớp Vỏ Tinh Thể",
    "crystalline-exoskeleton": "Crystalline Exoskeleton",
    "duoi-bo-cap": "Đuôi Bọ Cạp",
    "fracture": "Fracture",
    "giam-cam": "Giam Cầm",
    "impale": "Impale",
    "suc-manh-hop-am": "Sức Mạnh Hợp Âm",
    "power-chord": "Power Chord",
    "anh-hung-ca": "Anh Hùng Ca",
    "hymn-of-valor": "Hymn of Valor",
    "giai-dieu-khich-le": "Giai Điệu Khích Lệ",
    "aria-of-perseverance": "Aria of Perseverance",
    "ban-nhac-toc-do": "Bản Nhạc Tốc Độ",
    "song-of-celerity": "Song of Celerity",
    "khuc-cao-trao": "Khúc Cao Trào",
    "crescendo": "Crescendo",
    "cuu-roi": "Cứu Rỗi",
    "salvation": "Salvation",
    "van-tinh": "Vẫn Tinh",
    "starcall": "Starcall",
    "tinh-tu-ho-menh": "Tinh Tú Hộ Mệnh",
    "astral-infusion": "Astral Infusion",
    "diem-phan-cuc": "Điểm Phân Cực",
    "equinox": "Equinox",
    "nguyen-uoc": "Nguyện Ước",
    "wish": "Wish",
    "chim-an-xac": "Chim Ăn Xác",
    "carrion-renewal": "Carrion Renewal",
    "pha-suc": "Phá Sức",
    "decrepify": "Decrepify",
    "troi-buoc": "Trói Buộc",
    "nevermove": "Nevermove",
    "tra-tan": "Tra Tấn",
    "torment": "Torment",
    "chim-quy-hung-ton": "Chim Quỷ Hung Tợn",
    "ravenous-flock": "Ravenous Flock",
    "toi-thuong": "Tối Thượng",
    "transcendent": "Transcendent",
    "qua-cau-bong-toi": "Quả Cầu Bóng Tối",
    "dark-sphere": "Dark Sphere",
    "y-luc": "Ý Lực",
    "force-of-will": "Force of Will",
    "quet-tan-ke-yeu": "Quét Tan Kẻ Yếu",
    "scatter-the-weak": "Scatter the Weak",
    "bung-no-suc-manh": "Bùng Nổ Sức Mạnh",
    "unleashed-power": "Unleashed Power",
    "khau-vi-doc-dao": "Khẩu Vị Độc Đáo",
    "an-acquired-taste": "An Acquired Taste",
    "roi-luoi": "Roi Lưỡi",
    "tongue-lash": "Tongue Lash",
    "danh-chen": "Đánh Chén",
    "devour": "Devour",
    "da-day": "Da Dày",
    "thick-skin": "Thick Skin",
    "du-ngoan-thuy-vuc": "Du Ngoạn Thủy Vực",
    "abyssal-voyage": "Abyssal Voyage",
    "luot-tuong": "Lướt Tường",
    "rock-surfing": "Rock Surfing",
    "phi-thach": "Phi Thạch",
    "threaded-volley": "Threaded Volley",
    "quang-dia-chan": "Quăng Địa Chấn",
    "seismic-shove": "Seismic Shove",
    "tam-tham-bat-on": "Tấm Thảm Bất Ổn",
    "unraveled-earth": "Unraveled Earth",
    "mat-dat-day-song": "Mặt Đất Dậy Sóng",
    "weavers-wall": "Weaver's Wall",
    "luoi-dao-ket-lieu": "Lưỡi Dao Kết Liễu",
    "blades-end": "Blade's End",
    "ngoai-giao-kieu-noxus": "Ngoại Giao Kiểu Noxus",
    "noxian-diplomacy": "Noxian Diplomacy",
    "am-khi": "Ám Khí",
    "rake": "Rake",
    "con-duong-thich-khach": "Con Đường Thích Khách",
    "assassins-path": "Assassin's Path",
    "sat-thu-vo-hinh": "Sát Thủ Vô Hình",
    "shadow-assault": "Shadow Assault",
    "can-dam": "Can Đảm",
    "bravado": "Bravado",
    "anh-sang-tinh-tu": "Ánh Sáng Tinh Tú",
    "starlights-touch": "Starlight's Touch",
    "phao-dai-kien-co": "Pháo Đài Kiên Cố",
    "bastion": "Bastion",
    "choi-loa": "Chói Lóa",
    "dazzle": "Dazzle",
    "vu-tru-rang-ngoi": "Vũ Trụ Rạng Ngời",
    "cosmic-radiance": "Cosmic Radiance",
    "chien-tranh-du-kich": "Chiến Tranh Du Kích",
    "guerrilla-warfare": "Guerrilla Warfare",
    "phi-tieu-mu": "Phi Tiêu Mù",
    "blinding-dart": "Blinding Dart",
    "chay-le": "Chạy Lẹ",
    "move-quick": "Move Quick",
    "ban-doc": "Bắn Độc",
    "toxic-shot": "Toxic Shot",
    "bay-doc-noxus": "Bẫy Độc Noxus",
    "noxious-trap": "Noxious Trap",
    "doa-day": "Đọa Đầy",
    "damnation": "Damnation",
    "an-tu": "Án Tử",
    "death-sentence": "Death Sentence",
    "con-duong-tam-toi": "Con Đường Tăm Tối",
    "dark-passage": "Dark Passage",
    "luoi-hai-xoay": "Lưỡi Hái Xoáy",
    "flay": "Flay",
    "dong-hop": "Đóng Hộp",
    "the-box": "The Box",
    "ngam-ban": "Ngắm Bắn",
    "draw-a-bead": "Draw a Bead",
    "sung-lien-thanh": "Súng Liên Thanh",
    "rapid-fire": "Rapid Fire",
    "phong-nhay-ten-lua": "Phóng Nhảy Tên Lửa",
    "rocket-jump": "Rocket Jump",
    "boc-thuoc-sung": "Bọc Thuốc Súng",
    "explosive-charge": "Explosive Charge",
    "dai-bac-day-lui": "Đại Bác Đẩy Lùi",
    "buster-shot": "Buster Shot",
    "cong-pham-dai-vuong": "Cống Phẩm Đại Vương",
    "kings-tribute": "King's Tribute",
    "nhai-nuot": "Nhai Nuốt",
    "chomp": "Chomp",
    "vuong-quoc-bang-han": "Vương Quốc Băng Hàn",
    "frozen-domain": "Frozen Domain",
    "cot-bang": "Cột Băng",
    "pillar-of-ice": "Pillar of Ice",
    "chinh-phuc": "Chinh Phục",
    "subjugate": "Subjugate",
    "cuong-no-chien-truong": "Cuồng Nộ Chiến Trường",
    "battle-fury": "Battle Fury",
    "say-mau": "Say Máu",
    "bloodlust": "Bloodlust",
    "tieng-thet-uy-hiep": "Tiếng Thét Uy Hiếp",
    "mocking-shout": "Mocking Shout",
    "chem-xoay": "Chém Xoáy",
    "spinning-slash": "Spinning Slash",
    "tu-choi-tu-than": "Từ Chối Tử Thần",
    "undying-rage": "Undying Rage",
    "gian-lan": "Gian Lận",
    "loaded-dice": "Loaded Dice",
    "phi-bai": "Phi Bài",
    "wild-cards": "Wild Cards",
    "chon-bai": "Chọn Bài",
    "pick-a-card": "Pick A Card",
    "trao-bai": "Tráo Bài",
    "stacked-deck": "Stacked Deck",
    "dinh-menh": "Định Mệnh",
    "destiny": "Destiny",
    "doc-chet-nguoi": "Độc Chết Người",
    "deadly-venom": "Deadly Venom",
    "ambush": "Ambush",
    "doc-suy-nhuoc": "Độc Suy Nhược",
    "venom-cask": "Venom Cask",
    "nhiem-khuan": "Nhiễm Khuẩn",
    "contaminate": "Contaminate",
    "nham-mat-ban-bua": "Nhắm Mắt Bắn Bừa",
    "spray-and-pray": "Spray and Pray",
    "su-linh-hoat-cua-khi": "Sự Linh Hoạt Của Khỉ",
    "monkeys-agility": "Monkey's Agility",
    "vo-ho": "Võ Hổ",
    "tiger-stance": "Tiger Stance",
    "vo-rua": "Võ Rùa",
    "turtle-stance": "Turtle Stance",
    "vo-gau": "Võ Gấu",
    "bear-stance": "Bear Stance",
    "vo-phuong-hoang": "Võ Phượng Hoàng",
    "phoenix-stance": "Phoenix Stance",
    "dan-zaun": "Đạn Zaun",
    "zaun-touched-bolt-augmenter": "Zaun-Touched Bolt Augmenter",
    "tho-san-axit": "Thợ Săn Axit",
    "acid-hunter": "Acid Hunter",
    "tu-dien-kinh-hoang": "Tụ Điện Kinh Hoàng",
    "terror-capacitor": "Terror Capacitor",
    "luu-dan-an-mon": "Lựu Đạn Ăn Mòn",
    "noxian-corrosive-charge": "Noxian Corrosive Charge",
    "hoan-doi-vi-tri": "Hoán Đổi Vị Trí",
    "hyper-kinetic-position-reverser": "Hyper-Kinetic Position Reverser",
    "suc-manh-bao-thu": "Sức Mạnh Báo Thù",
    "living-vengeance": "Living Vengeance",
    "mui-ten-xuyen-pha": "Mũi Tên Xuyên Phá",
    "piercing-arrow": "Piercing Arrow",
    "ten-doc": "Tên Độc",
    "blighted-quiver": "Blighted Quiver",
    "mua-ten": "Mưa Tên",
    "hail-of-arrows": "Hail of Arrows",
    "soi-xich-toi-loi": "Sợi Xích Tội Lỗi",
    "chain-of-corruption": "Chain of Corruption",
    "tho-san-bong-dem": "Thợ Săn Bóng Đêm",
    "night-hunter": "Night Hunter",
    "nhao-lon": "Nhào Lộn",
    "tumble": "Tumble",
    "mui-ten-bac": "Mũi Tên Bạc",
    "silver-bolts": "Silver Bolts",
    "ket-an": "Kết Án",
    "condemn": "Condemn",
    "gio-khac-cuoi-cung": "Giờ Khắc Cuối Cùng",
    "final-hour": "Final Hour",
    "suc-manh-quy-quyet": "Sức Mạnh Quỷ Quyệt",
    "phenomenal-evil-power": "Phenomenal Evil Power",
    "diem-go": "Điềm Gở",
    "baleful-strike": "Baleful Strike",
    "thien-thach-den": "Thiên Thạch Đen",
    "dark-matter": "Dark Matter",
    "be-cong-khong-gian": "Bẻ Cong Không Gian",
    "event-horizon": "Event Horizon",
    "vu-no-vu-tru": "Vụ Nổ Vũ Trụ",
    "primordial-burst": "Primordial Burst",
    "phan-ra-huu-co": "Phân Rã Hữu Cơ",
    "organic-deconstruction": "Organic Deconstruction",
    "phan-hach-plasma": "Phân Hạch Plasma",
    "plasma-fission": "Plasma Fission",
    "vet-rach-hu-khong": "Vết Rách Hư Không",
    "void-rift": "Void Rift",
    "pha-vo-ket-cau": "Phá Vỡ Kết Cấu",
    "tectonic-disruption": "Tectonic Disruption",
    "tia-phan-huy-su-song": "Tia Phân Hủy Sự Sống",
    "life-form-disintegration-ray": "Life Form Disintegration Ray",
    "giap-chong-chat-no": "Giáp Chống Chất Nổ",
    "blast-shield": "Blast Shield",
    "cu-dam-bung-no": "Cú Đấm Bùng Nổ",
    "vault-breaker": "Vault Breaker",
    "cu-dam-pha-giap": "Cú Đấm Phá Giáp",
    "denting-blows": "Denting Blows",
    "cu-dam-xuyen-thau": "Cú Đấm Xuyên Thấu",
    "excessive-force": "Excessive Force",
    "ta-xung-huu-dot": "Tả Xung Hữu Đột",
    "assault-and-battery": "Assault and Battery",
    "tien-hoa-huy-hoang": "Tiến Hóa Huy Hoàng",
    "glorious-evolution": "Glorious Evolution",
    "chuyen-hoa-nang-luong": "Chuyển Hóa Năng Lượng",
    "siphon-power": "Siphon Power",
    "truong-trong-luc": "Trường Trọng Lực",
    "gravity-field": "Gravity Field",
    "tia-chet-choc": "Tia Chết Chóc",
    "death-ray": "Death Ray",
    "bao-dien-tu": "Bão Điện Từ",
    "chaos-storm": "Chaos Storm",
    "huyet-the": "Huyết Thệ",
    "crimson-pact": "Crimson Pact",
    "truyen-mau": "Truyền Máu",
    "transfusion": "Transfusion",
    "ho-mau": "Hồ Máu",
    "sanguine-pool": "Sanguine Pool",
    "thuy-trieu-mau": "Thủy Triều Máu",
    "tides-of-blood": "Tides of Blood",
    "mau-doc": "Máu Độc",
    "hemoplague": "Hemoplague",
    "dua-con-cua-bao": "Đứa Con Của Bão",
    "chosen-of-the-storm": "Chosen of the Storm",
    "truy-kich-": "Truy Kích ",
    "rolling-thunder": "Rolling Thunder",
    "noi-dien": "Nổi điên",
    "frenzy": "Frenzy",
    "sam-gam": "Sấm Gầm",
    "majestic-roar": "Majestic Roar",
    "vuot-sam-set": "Vuốt Sấm Sét",
    "thunder-claws": "Thunder Claws",
    "con-khat-vinh-cuu": "Cơn Khát Vĩnh Cửu",
    "eternal-thirst": "Eternal Thirst",
    "cu-va-doi-khat": "Cú Vả Đói Khát",
    "hungering-strike": "Hungering Strike",
    "tieng-hu-san-moi": "Tiếng Hú Săn Mồi",
    "hunters-call": "Hunters Call",
    "mui-mau": "Mùi Máu",
    "blood-scent": "Blood Scent",
    "soi-dien": "Sói Điên",
    "infinite-duress": "Infinite Duress",
    "ap-xung-nang-luong": "Áp Xung Năng Lượng",
    "mana-surge": "Mana Surge",
    "xung-kich-nang-luong": "Xung Kích Năng Lượng",
    "arcanopulse": "Arcanopulse",
    "vu-no-nang-luong": "Vụ Nổ Năng Lượng",
    "eye-of-destruction": "Eye of Destruction",
    "dien-tich-cau": "Điện Tích Cầu",
    "shocking-orb": "Shocking Orb",
    "nghi-thuc-ma-phap": "Nghi Thức Ma Pháp",
    "rite-of-the-arcane": "Rite of the Arcane",
    "thach-dau": "Thách Đấu",
    "challenge": "Challenge",
    "lien-hoan-tam-kich": "Liên Hoàn Tam Kích",
    "three-talon-strike": "Three Talon Strike",
    "tieng-het-xung-tran": "Tiếng Hét Xung Trận",
    "battle-cry": "Battle Cry",
    "can-truong": "Can Trường",
    "audacious-charge": "Audacious Charge",
    "ban-nguyet-thuong": "Bán Nguyệt Thương",
    "crescent-sweep": "Crescent Sweep",
    "dao-cua-lang-khach": "Đạo của Lãng Khách",
    "way-of-the-wanderer": "Way of the Wanderer",
    "bao-kiem": "Bão Kiếm",
    "steel-tempest": "Steel Tempest",
    "tuong-gio": "Tường Gió",
    "wind-wall": "Wind Wall",
    "quet-kiem": "Quét Kiếm",
    "sweeping-blade": "Sweeping Blade",
    "tran-troi": "Trăn Trối",
    "last-breath": "Last Breath",
    "dan-dat-linh-hon": "Dẫn Dắt Linh Hồn",
    "shepherd-of-souls": "Shepherd of Souls",
    "tu-le": "Tử Lễ",
    "last-rites": "Last Rites",
    "vong-tron-tam-toi": "Vòng Tròn Tăm Tối",
    "dark-procession": "Dark Procession",
    "man-suong-than-khoc": "Màn Sương Than Khóc",
    "mourning-mist": "Mourning Mist",
    "khuc-ca-hac-am": "Khúc Ca Hắc Ám",
    "eulogy-of-the-isles": "Eulogy of the Isles",
    "phan-bao": "Phân Bào",
    "cell-division": "Cell Division",
    "ban-tay-co-gian": "Bàn Tay Co Giãn",
    "stretching-strike": "Stretching Strike",
    "chat-bat-on": "Chất Bất Ổn",
    "unstable-matter": "Unstable Matter",
    "sung-cao-su-": "Súng Cao Su ",
    "elastic-slingshot": "Elastic Slingshot",
    "nay-nay-nay": "Nảy Nảy Nảy!",
    "lets-bounce": "Let's Bounce!",
    "khinh-thuong-ke-yeu": "Khinh Thường Kẻ Yếu",
    "contempt-for-the-weak": "Contempt for the Weak",
    "phi-tieu-sac-lem": "Phi Tiêu Sắc Lẻm",
    "razor-shuriken": "Razor Shuriken",
    "phan-than-bong-toi": "Phân Thân Bóng Tối",
    "living-shadow": "Living Shadow",
    "duong-kiem-bong-toi": "Đường Kiếm Bóng Tối",
    "shadow-slash": "Shadow Slash",
    "dau-an-tu-than": "Dấu Ấn Tử Thần",
    "death-mark": "Death Mark",
    "de-noi-dien": "Dễ Nổi Điên",
    "short-fuse": "Short Fuse",
    "bom-nay": "Bom Nảy",
    "bouncing-bomb": "Bouncing Bomb",
    "goi-chat-no": "Gói Chất Nổ",
    "satchel-charge": "Satchel Charge",
    "bai-min": "Bãi Mìn",
    "hexplosive-minefield": "Hexplosive Minefield",
    "sieu-bom-dia-nguc": "Siêu Bom Địa Ngục",
    "mega-inferno-bomb": "Mega Inferno Bomb",
    "lo-tru-thoi-gian": "Lọ Trữ Thời Gian",
    "time-in-a-bottle": "Time in a Bottle",
    "bom-hen-gio": "Bom Hẹn Giờ",
    "time-bomb": "Time Bomb",
    "rut-ngan-thoi-gian": "Rút Ngắn Thời Gian",
    "rewind": "Rewind",
    "be-cong-thoi-gian": "Bẻ Cong Thời Gian",
    "time-warp": "Time Warp",
    "dao-nguoc-thoi-gian": "Đảo Ngược Thời Gian",
    "chronoshift": "Chronoshift",
    "khu-vuon-gai-goc": "Khu Vườn Gai Góc",
    "garden-of-thorns": "Garden of Thorns",
    "no-ro": "Nở Rộ",
    "deadly-spines": "Deadly Spines",
    "xum-xue": "Xum Xuê",
    "rampant-growth": "Rampant Growth",
    "re-cay": "Rễ Cây",
    "grasping-roots": "Grasping Roots",
    "day-gai": "Dây Gai",
    "stranglethorns": "Stranglethorns"
}

export function registerEmoji(code, url) {
  code = code.toLowerCase();
  extendedEmoji[code] = url;
}

export function emojiList() {
  const result = emoji.slice(0);
  _.each(extendedEmoji, (v,k) => result.push(k));
  return result;
}

const emojiHash = {};

// add all default emojis
emoji.forEach(code => emojiHash[code] = true);

// and their aliases
const aliasHash = {};
Object.keys(aliases).forEach(name => {
  aliases[name].forEach(alias => aliasHash[alias] = name);
});

export function performEmojiUnescape(string, opts) {
  // this can be further improved by supporting matches of emoticons that don't begin with a colon
  if (string.indexOf(":") >= 0) {
    return string.replace(/\B:[^\s:]+:?\B/g, m => {
      const isEmoticon = !!translations[m];
      const emojiVal = isEmoticon ? translations[m] : m.slice(1, m.length - 1);
      const hasEndingColon = m.lastIndexOf(":") === m.length - 1;
      const url = buildEmojiUrl(emojiVal, opts);
      const classes = isCustomEmoji(emojiVal, opts) ? "emoji emoji-custom" : "emoji";

      if(isCustomEmoji(emojiVal, opts)){
                return ['a', {href: '//lmss.vn/wiki/' + emojiVal}, '<img src=\"' + url + '" title=\":' + emojiVal + ':\" class=\"' + classes +'\" alt=\":' + emojiVal +':\">' + " " + championName[emojiVal]];
            }else{
                return ['img', { href: url, title, 'class': classes, alt: emojiVal }];
            }

    });
  }

  return string;
}

export function isCustomEmoji(code, opts) {
  code = code.toLowerCase();
  if (extendedEmoji.hasOwnProperty(code)) return true;
  if (opts && opts.customEmoji && opts.customEmoji.hasOwnProperty(code)) return true;
  return false;
}

export function buildEmojiUrl(code, opts) {
  let url;
  code = code.toLowerCase();

  if (extendedEmoji.hasOwnProperty(code)) {
    url = extendedEmoji[code];
  }

  if (opts && opts.customEmoji && opts.customEmoji[code]) {
    url = opts.customEmoji[code];
  }

  if (!url && emojiHash.hasOwnProperty(code)) {
    url = opts.getURL(`/images/emoji/${opts.emojiSet}/${code}.png`);
  }

  if (url) {
    url = url + "?v=" + IMAGE_VERSION;
  }

  return url;
}

export function emojiExists(code) {
  code = code.toLowerCase();
  return !!(extendedEmoji.hasOwnProperty(code) || emojiHash.hasOwnProperty(code));
};

let toSearch;
export function emojiSearch(term, options) {
  const maxResults = (options && options["maxResults"]) || -1;
  if (maxResults === 0) { return []; }

  toSearch = toSearch || _.union(_.keys(emojiHash), _.keys(extendedEmoji), _.keys(aliasHash)).sort();

  const results = [];

  function addResult(t) {
    const val = aliasHash[t] || t;
    if (results.indexOf(val) === -1) {
      results.push(val);
    }
    return maxResults > 0 && results.length >= maxResults;
  }

  for (let i=0; i<toSearch.length; i++) {
    const item = toSearch[i];
    if (item.indexOf(term) === 0 && addResult(item)) {
      return results;
    }
  }

  for (let i=0; i<toSearch.length; i++) {
    const item = toSearch[i];
    if (item.indexOf(term) > 0 && addResult(item)) {
      return results;
    }
  }

  return results;
};
